### ISSUE TITLE
Key-only policy annotation

### ISSUE THREAD

**Issue by 0x00A5** [cedar-policy/cedar#1031]
### Describe the improvement you'd like to request

As of writing, policy annotations are required to be key-value pairs. When using it as a tag or label for marking a policy, this becomes a bit awkward. For example, we'd like to write a policy like the following to mark a policy as shadow / dry-run mode.

```
@shadow_mode
permit(principal, action, resource);
```
This annotation is illegal and we have to write the annotation as `@shadow_mode("")`.

### Describe alternatives you've considered

Assign an empty string to the annotations that serve only as a tag.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this internal improvement
- [ ] ⚠️ This feature might incur a breaking change

**Comment by aaronjeline** [comment]
This seems very reasonable

**Comment by khieta** [comment]
Thanks for filing this issue! Agreed that this seems reasonable, but I don't think it's high on our priority list. I'll mark it as `help-wanted` to indicate that we'd accept a PR for this. I think the only code that would need to be edited is the [policy parser](https://github.com/cedar-policy/cedar/tree/main/cedar-policy-core/src/parser).

**Comment by john-h-kastner-aws** [comment]
FYI, we've implemented this for release in an upcoming version 4.2. `@shadow_mode` will now be valid an equivalent to `@shadow_mode("")`
