### ISSUE TITLE
(De-)serialization of PatternElem under the Arbitrary feature

### ISSUE THREAD

**Issue by Brandon-Rozek** [cedar-policy/cedar#1042]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Other

### Describe the bug

De-serializing using `serde_json` during fuzzing leads to a panic when `non_scope_constraints` contain unicode escape sequences in the `LIKE` sub-expression.

### Expected behavior

De-serialization to not lead to a panic

### Reproduction steps

1. Install Cedar and Cedar-drt
2. In the fuzz source generate a random policy when implementing `Arbitrary`
```
let schema: Schema = Schema::arbitrary(SETTINGS.clone(), u)?;
let hierarchy = schema.arbitrary_hierarchy(u)?;
let policy = schema.arbitrary_policy(&hierarchy, u)?;
```
3. Serialize and de-serialize using serde
```
let nsc: ast::Expr = policy.non_scope_constraints().to_owned();
let nsc_string = serde_json::to_string(&nsc)
    .expect("serialization failed");
let nsc_rt: ast::Expr = serde_json::from_str(nsc_string.as_ref())
    .expect("deserialization failed"); // Panic occurs here
```

### Code Snippet

```rust
// Example failure case
let expr: Expr = Expr::like(Expr::var(Var::Principal), vec![PatternElem::Char('\0')]);
let expr_string = serde_json::to_string(&expr)
    .expect("serialization failed");
let expr_rt: Expr = serde_json::from_str(expr_string.as_ref())
    .expect("deserialization failed"); // Panic occurs here
```

### Log output

```
deserialization failed: Error("invalid type: integer `0`, expected a character", line: 1, column: 459)
```

### Operating  System

Linux

### Additional information and screenshots

From some investigation, it looks like this might be because of the Serialize implementation of `PatternElem` in the file `cedar/cedar-policy-core/src/ast/pattern.rs`. It converts the character to a `u32` primitive.

The serializer is defined under the `cfg(feature = "arbitrary")` which is active during fuzzing. There isn't a corresponding `Deserialize` implementation which undoes the `u32` conversion.

**Comment by shaobo-he-aws** [comment]
We have switched to Lean so we should be able to just deserialize the character.
