### ISSUE TITLE
[3.x.x only] Converting a JSON-syntax schema to human syntax and back can change the target of an entity type reference

### ISSUE THREAD

**Issue by cdisselkoen** [cedar-policy/cedar#1063]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Schemas and Validation

### Describe the bug

For the following schema:

```
{
  "": {
    "entityTypes": {
      "User": {}
    },
    "actions": {}
  },
  "NS": {
    "commonTypes": {
      "User": { "type": "String" }
    },
    "entityTypes": {
      "Foo": {
        "shape": {
          "type": "Record",
          "attributes": {
            "owner": { "type": "Entity", "name": "User" }
          }
        }
      }
    },
    "actions": {}
  }
}
```

When converted to natural/human syntax, we get
```
namespace NS {
  type User = __cedar::String;
  entity Foo = {"owner": User};
}
entity User;
```
(I added whitespace for clarity.)

When converting that back to JSON syntax, we get
```
{
  "NS": {
    "commonTypes": {
      "User": { "type":"String" }
    },
    "entityTypes": {
      "Foo": {
        "shape": {
          "type": "Record",
          "attributes": {
            "owner": { "type": "User" }
          }
        }
      }
    },
    "actions": {}
  },
  "": {
    "entityTypes": {
      "User": {}
    },
    "actions": {}
  }
}
```
(again, I added whitespace for clarity.)

This is not the same as the original schema: In the original schema, `Foo.owner` had the type `User`, an entity type in the empty namespace.  In the final schema, `Foo.owner` has the type `NS::User`, a common type which resolves to `String`.

Due to the under-the-hood implementation where natural-syntax schemas are first translated into the JSON structures before processing, I'm pretty sure that in 3.2.1, the behavior of the natural-syntax schema is the same as that of the final schema.  An important question is whether this is the _correct_ behavior for the natural-syntax schema, according to the spec.  I believe it is (even after #579 is fixed), because priority is given to definitions in the current namespace over definitions in the empty namespace.  (RFC 24 also specifies that common-type definitions take priority over entity-type definitions, but I interpret that to be "in the same namespace", so it doesn't apply here.  I also apply that interpretation in #1060.)

Assuming that the 3.2.1 interpretation of this natural-syntax schema is correct, the problem is in the first step above (converting from JSON to natural syntax), so probably in `json_schema_to_custom_schema_str()` in `human_schema/fmt.rs`.  This means the bug only affects the translation from JSON to human/natural syntax, and not the interpretation of any JSON or natural-syntax schemas in 3.2.1.

### Expected behavior

Converting the JSON schema to natural/human syntax and back should yield the same schema, or at least an equivalent one.

### Reproduction steps

1. I reproduced this with the 3.2.1 CLI. `cargo install cedar-policy-cli@3.2.1`
2. Save the initial schema above as `cedarschema.json`
3. `cedar translate-schema --direction json-to-human --schema cedarschema.json > cedarschema`
4. `cedarschema` should match what's written above, modulo whitespace
5. `cedar translate-schema --direction human-to-json --schema cedarschema > cedarschema_roundtripped.json`
6. `cedarschema_roundtripped.json` should match the final schema above, modulo whitespace

### Additional configuration

Reproduced on the 3.2.1 CLI

**Comment by cdisselkoen** [comment]
Noting that this issue is moot with [RFC 70](https://github.com/cedar-policy/rfcs/pull/70), as all three of the schemas above are invalid after RFC 70.  However, we should still consider whether we need to fix this in 3.x (or any other versions that are released before RFC 70 ships, assuming it does indeed eventually ship).

**Comment by shaobo-he-aws** [comment]
I think a proper fix is essentially RFC 70.

**Comment by cdisselkoen** [comment]
Correct, the only question is do we want a (different, backwards-compatible) fix for 3.x

**Comment by john-h-kastner-aws** [comment]
Proposed fix for 3.x: I will extend the check for `NameCollisions` errors reported by `json_schema_to_custom_schema_str` to also look for collisions between types declared in the empty namespace and the (unqualified) type name for types declared any namespace.

With this change, an error would be reported at step 3 in the reproduction steps. There will be no change in the what schema are accepted by the main schema parsing functions.

**Comment by cdisselkoen** [comment]
Sounds reasonable
