### ISSUE TITLE
Implement RFC 70: Disallow shadowing definitions in the empty namespace

### ISSUE THREAD

**Issue by cdisselkoen** [cedar-policy/cedar#1106]
### Category

Cedar language or syntax features/changes

### Describe the feature you'd like to request

Implement [RFC 70](https://github.com/cedar-policy/rfcs/blob/main/text/0070-disallow-empty-namespace-shadowing.md)

### Describe alternatives you've considered

N/A 

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by shaobo-he-aws** [comment]
Implemented via #1147
