### ISSUE TITLE
API to substitute all occurences of an entity literal with another entity literal

### ISSUE THREAD

**Issue by andrewmwells-amazon** [cedar-policy/cedar#1120]
### Category

User level API features/changes

### Describe the feature you'd like to request

An API to substitute all occurrences of an entity literal with another entity literal.

### Describe alternatives you've considered

Status quo

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by laraelangdon** [comment]
Should we cancel this now given latest clarified requirements?

**Comment by cdisselkoen** [comment]
Resolved by #1233
