### ISSUE TITLE
Add convenience methods for the number of the Policies and Templates in a PolicySet 

### ISSUE THREAD

**Issue by jv-garcia** [cedar-policy/cedar#1179]
### Category

User level API features/changes

### Describe the feature you'd like to request

Hey Cedar team,

My use case involves loading policies from a database and creating a `cedar_policy::PolicySet` with those. I'd like to introduce some assertions/safety checks so that I can make sure that the number of policies that I have in the policy set equals the amount of policies that I loaded.

To do this I suggest we add `cedar_policy::PolicySet::num_of_policies() -> usize` (happy to chat about the name, of course), and similar for templates. These methods would be simple proxies for the `HashMap::len()`.

### Describe alternatives you've considered

This is possible today using the provided iterators (like [here](https://github.com/cedar-policy/cedar/blob/12cbc257992fcc3ca7a38caf37c71766beb00eff/cedar-policy/src/api.rs#L2016)), but doing that requires consuming the iterator. A call to the`HashMap`'s `len()` would be more efficient.

### Additional context

I'm still using 2.4.x, so I need to to backport to that version.

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by khieta** [comment]
Resolved by #1180, which was included in the 2.5.0 and 3.4.0 releases.
