### ISSUE TITLE
Golang support

### ISSUE THREAD

**Issue by onitake** [cedar-policy/cedar#118]
### Category

Other

### Describe the feature you'd like to request

To make Cedar more useful, it would be nice to have native support for other languages besides Rust.

While it's possible to integrate with non-Rust runtimes via FFI, this is not an ideal approach for Go, where applications are typically compiled from complete source code into a static binary. With Rust FFI, it would be either necessary to distribute libraries for the various OS/architecture combinations supported by Go (for which there is currently no standardized way), or always compile the Rust code in-place (requiring a Rust build environment in addition to Go).

### Describe the solution you'd like

A Go-native implementation would be the ideal solution, reducing overhead and build dependencies.

### Describe alternatives you've considered

Alternatively, an SDK using a Go-Rust integration layer like https://github.com/mediremi/rust-plus-golang could be provided, but this doesn't solve the multiple-OS/CPU-architecture problem well.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by john-h-kastner-aws** [comment]
Thanks, for the request. We've heard from some others that easy integration with Go would be a useful feature, and there have even been some initial external efforts to develop this, but we do not expect to support any other bindings (or native implementations) ourselves. 

Two repositories I'm aware of have [WASM based](https://github.com/Joffref/cedar) and [CGO based](https://github.com/iann0036/cedargo) bindings for Go. I'm not well versed in Go, so I can't say if these satisfy your particular requests, but they may be a useful starting point.

**Comment by andrewmwells-amazon** [comment]
Closing this as it's been stale for a while. Please look at the linked Go bindings from John's post ([WASM based](https://github.com/Joffref/cedar) and [CGO based](https://github.com/iann0036/cedargo)) and let us know if you run into issues that are in scope for Cedar.
