### ISSUE TITLE
Support `like` on entity ID patterns

### ISSUE THREAD

**Issue by WanderingStar** [cedar-policy/cedar#119]
### Category

Cedar language features

### Describe the feature you'd like to request

We would like to be able to match entities based on patterns in their entity IDs. For example, we would like to be able to express conditions like "is a Photo with an entity ID matching VacationPhoto*.jpg".

### Describe the solution you'd like

We propose using the existing `like` keyword, but allowing an entity pattern to appear on the RHS, not just a literal string. The entity pattern would look like a typical entity, but the ID string would be interpreted as `like` matching currently is.

Sample policy:
```
permit(
  principal == User::"alice", 
  action    == Action::"update", 
  resource
)
when {  resource like Photo::"VacationPhoto*.jpg" };
```

### Describe alternatives you've considered

Alternative solutions:
Using a different keyword than `like` would be fine.

Using an attribute check combined with a type check (see https://github.com/cedar-policy/cedar/issues/94) would work, but would require duplicated information in the entity (the entity ID and the attribute must match). Eg.
```
when {
  resource.filename like "VacationPhoto*.jpg" 
  && resource is Photo
}
```

Using an attribute check, combined with a group membership check (see https://github.com/cedar-policy/cedar/issues/94#issuecomment-1570682802) would work, but would require the parent to be set. Eg.
```
when {
  resource.filename like "VacationPhoto*.jpg" 
  && resource in ResourceGroup::"Photos"
}
```

Using two attribute checks, one for the type and another for the ID would work, but using string comparison for type comparisons seems suspect. Eg.
```
when {
  resource.filename like "VacationPhoto*.jpg" 
  && resource.type == "Photo"
}
```

Using an attribute check on an attribute which includes both the type and ID would work, but again uses string comparison for type comparisons:
```
when {
  resource.typeAndFilename like "Photo::VacationPhoto*.jpg" 
}
```

### Additional context

This was split out from https://github.com/cedar-policy/cedar/issues/95

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cdisselkoen** [comment]
Something we should consider, if we implement this, is whether the pattern has to specifically match the EID or whether it can match the entire UID.  Example:
```
// #119 proposes this be allowed
resource like Photo::"VacationPhoto*.jpg"

// should this be allowed?
resource like MyCorp::*::Photo::"private.jpg"

// or even this?
resource like Photo*::"private.jpg"
```
And regardless of what we decide, another question is will the resulting behavior be clear to customers.  E.g., if we only support the first form, will customers be confused if the second or third forms don't work.

**Comment by john-h-kastner-aws** [comment]
For your application, how important is it that this data is stored in the EID? Could it be stored _only_ in an attribute to avoid duplicating the data?

In our docs we strongly encourage using UUIDs for EIDs, and I feel adding this feature may incline users to do the opposite.

https://docs.cedarpolicy.com/syntax-entity.html

> We recommend that you use values like [universally unique identifiers (UUIDs)](https://wikipedia.org/wiki/Universally_unique_identifier). For example, if user jane leaves the company, and you later let someone else use the name jane, then that new user automatically gets access to everything granted by policies that still reference User::"jane".
> 
> Cedar can’t distinguish between the new user and the old. This applies to both principal and resource identifiers. Always use identifiers that are guaranteed unique and never reused to ensure that you don’t unintentionally grant access because of the presence of an old identifier in a policy.

**Comment by WanderingStar** [comment]
Seems like the RFC process is better for this: https://github.com/cedar-policy/rfcs

**Comment by andrewmwells-amazon** [comment]
Closing this for now. Not sure if you found a work around, but if not (or if you still think this would be a generally useful feature) feel free to open an RFC.

**Comment by WanderingStar** [comment]
Thanks. This was tied to our attempts to use template linking, and we've decided to try a separate templating step instead, so yes we have a workaround.
