### ISSUE TITLE
Tests failing on `main` for `cedar-policy-core` and `cedar-policy-core` with `--no-default-features`

### ISSUE THREAD

**Issue by cdisselkoen** [cedar-policy/cedar#120]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+) and [discussions](https://github.com/cedar-policy/cedar/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Policy Evaluation

### Describe the bug

`cedar-policy-core` has features for the `ipaddr` and `decimal` extensions, which are optional but enabled by default.  But if you actually disable them, tests are not passing.

### Expected behavior

`cargo test --no-default-features` should pass.

### Reproduction steps

1. Clone this repo on `main` (I reproduced on 4b9e8b4)
2. `cd cedar-policy-core` or `cd cedar-policy-validator`
3. `cargo test --no-default-features`

### Log output

```
< snipped output above this, assuming that this is reproducible >

failures:
    entities::json_parsing_tests::more_escapes
    entities::schema_based_parsing_tests::missing_record_attr
    entities::schema_based_parsing_tests::parents_wrong_type
    entities::schema_based_parsing_tests::type_mismatch_entity_record
    entities::schema_based_parsing_tests::type_mismatch_entity_types
    entities::schema_based_parsing_tests::type_mismatch_extension_types
    entities::schema_based_parsing_tests::type_mismatch_in_record_attr
    entities::schema_based_parsing_tests::type_mismatch_set_element
    entities::schema_based_parsing_tests::type_mismatch_string_long
    entities::schema_based_parsing_tests::unexpected_entity_attr
    entities::schema_based_parsing_tests::unexpected_record_attr
    entities::schema_based_parsing_tests::with_and_without_schema
    evaluator::test::partial_ext_unfold
    evaluator::test::restricted_expressions

test result: FAILED. 318 passed; 14 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.36s

error: test failed, to rerun pass `--lib`
```

**Comment by john-h-kastner-aws** [comment]
The obvious actions to take from this (aside from fixing the tests) is to add a `--no-default-features`  test run to our CI. Are there any other test configurations we might be missing?

**Comment by andrewmwells-amazon** [comment]
> The obvious actions to take from this (aside from fixing the tests) is to add a --no-default-features test run to our CI. Are there any other test configurations we might be missing?

Have PR for this here:
https://github.com/cedar-policy/cedar/pull/136

**Comment by andrewmwells-amazon** [comment]
Nightly build are succeeding with `--no-default-features` so I'm closing this issue.

**Comment by andrewmwells-amazon** [comment]
> Nightly build are succeeding with `--no-default-features` so I'm closing this issue.

https://github.com/cedar-policy/cedar/actions/runs/5417864990

**Comment by cdisselkoen** [comment]
Still fails for me on `main` with the reproduction steps listed in the issue

**Comment by andrewmwells-amazon** [comment]
The build should be fixed with https://github.com/cedar-policy/cedar/pull/179. We'll still need to run with `--no-default-features` on member of the workspace.

**Comment by andrewmwells-amazon** [comment]
Updated to include failure on `cedar-policy-validator`. https://github.com/cedar-policy/cedar/pull/179 should fix both and add CI runs.
