### ISSUE TITLE
Provide the `@id` annotation from the CLI as a library feature

### ISSUE THREAD

**Issue by aaronjeline** [cedar-policy/cedar#127]
### Category

User level API changes

### Describe the feature you'd like to request

The Cedar language provides a general purpose annotation feature, allowing users to annotate policies w/ arbitrary key/value pairs, and consumers of policies can use these however they want. 

The Cedar CLI uses this in a very nice way to let you assign policy IDs to policies via annotations:
```
@id("myid")
permit(principal, action, resource);
```

This is a nice feature, and we should make it easy for other consumers of the Cedar library to use, instead of needing to re-roll it themselves.

### Describe the solution you'd like

Take the function from Cedar CLI that renames policies according to `@id` annotations, and move into the Cedar library and expose it.

### Describe alternatives you've considered

The alternative is not doing this. We don't enforce any semantics over annotations, and we may not want privilege certain interpretations. 

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by shaobo-he-aws** [comment]
Do you think this feature merits a RFC?

**Comment by aaronjeline** [comment]
I don't think so. It's not an addition to the language or change to any specs, it's just a utility functions for users. 
To be clear, annotations should still have no official semantics. Users should still be able to user them any way they want, this is just providing a common use-case.

**Comment by khieta** [comment]
What would the API for this new feature look like?

I feel like we don't want to assign special semantics to any annotations in the core library. But I can see how it would be useful to provide some simple examples of this for users (e.g., in the `cedar-examples` repo).

**Comment by aaronjeline** [comment]
I imagine the API would look like it does in Cedar CLI:
```
/// Renames policies and templates based on (@id("new_id") annotation.
/// If no such annotation exists, it keeps the current id.
fn rename_from_id_annotation(ps: PolicySet) -> PolicySet 
```


I understand not wanting in the Cedar SDK proper, to avoid asserting special semantics for specific annotations. If  we go this route, I'd at least like it to be an easily accessible example.

**Comment by andrewmwells-amazon** [comment]
Closing because we don't want to enforce semantics on annotations.
