### ISSUE TITLE
Support explicit enumerations in schemas

### ISSUE THREAD

**Issue by mwhicks1** [cedar-policy/cedar#128]
### Category

Cedar validation features

### Describe the feature you'd like to request

Add support for enumerations of `bool`, `string`, and `long` types in schemas, and use this information when doing policy validation.

### Describe the solution you'd like

Maintaining backward compatibility with JSON schema as much as possible, we can match its [`enum` feature](https://cswr.github.io/JsonSchema/spec/generic_keywords/#enumerated-values). For example:
```
"type": "Record",
  "attributes": {
    "color": {
      "type": "String"
      "enum": ["red", "blue", "green"]
    }
}
```
The `enum` part limits the `color` attribute to one of three possibilities. We would permit enumerations of this flavor for numbers and booleans too. 

We can extend the validator to support singleton types for strings and numbers, and to allow union types for strings, booleans, and numbers. We have singleton types for booleans already, where `bool` is equivalent to the union `true|false`. This feature would generalize the same approach to numbers and strings.

For the future addition of numeric ranges to schemas, you could technically have both enumerations and ranges, but the enumeration can be checked against the range at validation time, and then the range can be ignored.

### Describe alternatives you've considered

The only alternative is to not support the feature, or perhaps to support it using a different syntax.

### Additional context

Enumerations are a common need, and this change supports them in Cedar. It avoids the mistake of expecting a string (say) to match only a few values, but then it inadverentently matches too many.

Enumerations are particularly useful for policy building UIs -- the UI can look at the schema to know what values are valid for a particular attribute. 

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by aaronjeline** [comment]
Moved to [RFC 13](https://github.com/cedar-policy/rfcs/pull/13)
