### ISSUE TITLE
Improvements on schema parsing error messages

### ISSUE THREAD

**Issue by jv-garcia** [cedar-policy/cedar#130]
### Category

Cedar validation features

### Describe the feature you'd like to request

The following schema fails with a warning (tested with the PlayGround2):

```
{
    "Test::Namespace": {
        "actions": {
            "sampleAction": {
                "attributes": {},
                "appliesTo": {
                    "principalTypes": [],
                    "resourceTypes": [
                        "sampleResource"
                    ],
                    "context": {}
                }
            }
        },
        "entityTypes": {
            "sampleResource": {
                "shape": {
                    "type": "Record",
                    "attributes": {
                        "orgname": {
                            "type": "String"
                        }
                    }
                }
            }
        }
    }
}
```

The error message is: `JSON Schema file could not be parsed: data did not match any variant of untagged enum SchemaType at line 12 column 17`

The problem here is that currently `context` should either not be there or should be of type `Record`, but the message is quite confusing. Plus empty `context` seems reasonable...

### Describe the solution you'd like

Empty `context` should be accepted and valid.

### Describe alternatives you've considered

A better error message is displayed

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by shaobo-he-aws** [comment]
I changed the title of this issue to restrict the scope.

**Comment by shaobo-he-aws** [comment]
Here's another example:
```JSON
{
  "CedarTodo": {
    "entityTypes": {
      "Folder": {
        "shape": {
          "type": "Record",
          "attributes": {
            "id": {
              "type": "String",
              "required": true
            },
            "name": {
              "type": "String",
              "required": true
            }
          }
        }
      },
      "TodoList": {
        "shape": {
          "type": "Record",
          "memberOfTypes": ["Folder"],
          "attributes": {
            "id": {
              "type": "String"
            },
            "name": {
              "type": "String"
            }
          }
        }
      }
    },
    "actions": {}
  }
}
```
Within the `TodoList` entity, the `memberOfTypes` field is inside the `shape` field. This is the mistake. However, the error message I get is `Undeclared common types: {"Record"}`, which is completely unrelated.

**Comment by shaobo-he-aws** [comment]
Should we leave this issue open so that users don't have to create another issue when they want to report other improvements they want?
