### ISSUE TITLE
Add ability to create an Entity with tags in `Entity::new()`

### ISSUE THREAD

**Issue by a0js** [cedar-policy/cedar#1374]
### Category

User level API features/changes

### Describe the feature you'd like to request

The entity creation function has no way to create an entity with tags. I'd like to see tags added as an optional parameter to the `Entity::new()` function, and have them be used in authorization calculations. Additionally, a `tag` function that behaves similarly to the `attr` function, might be warranted.

### Describe alternatives you've considered

Another option would be to add an `update_tags` function, however that seems to go against the pattern of immutability I see in the current API for Entity.

### Additional context

The only way, currently, to include tags on the entity is to parse it from JSON.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by john-h-kastner-aws** [comment]
Thanks for opening this! We definitely should support this in the API. We unfortunately can't add a new parameter to `new` without a breaking change for existing callers and I agree that the mutable `update_tags` alternative isn't what we'd want to offer. This probably means adding a `new_with_tags` function in the minor version release, and possibly updating `new` whenever we want to release API version 5.0

**Comment by a0js** [comment]
`new_with_tags` seems appropriate to me. How frequently are minor versions released? I hope to be able to use such functionality sooner rather than later. I'm super new to rust, but I can try to make a PR.

**Comment by john-h-kastner-aws** [comment]
We don't have a specific cadence for releases, but we're looking at a minor release sometime in January
