### ISSUE TITLE
Cedar golang FFI

### ISSUE THREAD

**Issue by yuana97** [cedar-policy/cedar#146]
### Category

Cedar language features

### Describe the feature you'd like to request

library for calling Cedar from golang

### Describe the solution you'd like

A package similar to https://github.com/cedar-policy/cedar-java but for golang, approved for aws internal use

### Describe alternatives you've considered

Making our own. We just lack the dev time to expend on supporting this at the moment.

### Additional context

We're currently planning to use AVP but want to explore calling the cedar library directly

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by anwarmamat** [comment]
@yuana97 There are two external language bindings for Go. You can find them at: https://github.com/cedar-policy/cedar-awesome. Do you want to try them?

**Comment by andrewmwells-amazon** [comment]
Closing this for now. If try the linked bindings and find issues you think are in scope for Cedar, please let us know.
