### ISSUE TITLE
Improve validator error messages

### ISSUE THREAD

**Issue by mwhicks1** [cedar-policy/cedar#149]
### Category

Cedar validation features

### Describe the feature you'd like to request

The validator does not provide great error messages. Improve them.

The error messages should include:
- More context: When an attribute is missing, what entity is it missing from? (See example below)
- When an entity type in the `entityTypes` part of the schema has a blank string in its `memberOfTypes` array, the error message is about a parse error that suggests no obvious fix. In general, malformed schemas seem not to yield intuitive error messages.
- If you attempt to give an entity type a `shape` other than a record, you should get an error message that tells you that specifically

Additional context with use-cases below.

### Describe the solution you'd like

Per https://github.com/cedar-policy/cedar/issues/135 it might be nice to provide a (P,A,R,C) tuple that shows why something is an error, when that is possible.

### Describe alternatives you've considered

Nothing for it!

### Additional context

In [tinytodo](https://github.com/cedar-policy/cedar-examples/tree/main/tinytodo), when I comment out the `resource has owner &&` part of policy1 (the second policy) of `policies.cedar` and validate, I get this error:
```
[ tinytodo ]> cedar validate --schema tinytodo.cedarschema.json --policies policies.cedar 
Validation Results:
Validation error on policy policy1 at offset 300-314: Attribute not found in record or entity owner
```
It would be useful to know which type the attribute is missing from. Here, it should be the type `Application`.

If I introduce a typo, e.g., changing `resource.readers` to `resource.reders`, it's the same: The type (`List`) is not given when it says the attribute is not found.

---

In [tinytodo](https://github.com/cedar-policy/cedar-examples/tree/main/tinytodo), when I introduce a type error `when { 3 < resource.readers }` instead of `when { principal in resource.readers }` in policy2 (the third policy), I get the error `Expected one of [{"type":"Long"}] but saw {"type":"Entity","name":"Team"}`. It might be nice to make this more prosaic, e.g., `Expected type 'Long' but saw entity type 'Team'`.

---

In [tinytodo](https://github.com/cedar-policy/cedar-examples/tree/main/tinytodo), if I change `"Team"` on line 7 of `tinytodo.cedarschema.json` to be `""` instead (making an entity of type `User`'s `memberOfTypes` the empty string) I get the error: `failed to parse schema from file tinytodo.cedarschema.json: Parse error in entity type: 
  Unrecognized EOF found at 0
Expected one of ACTION, CONTEXT, ELSE, FALSE, FORBID, HAS, IDENTIFIER, IF, IN, LIKE, PERMIT, PRINCIPAL, RESOURCE, THEN, TRUE, UNLESS or WHEN` -- at the least it would be nice to know what line/column the error is on.

---

If just after line 86 of `tinytodo.cedarschema.json` I add `"context": {}` after the `resourceTypes: [ ... ]` part (adding a comma where needed), I get the cryptic error message `failed to parse schema from file tinytodo.cedarschema.json: JSON Schema file could not be parsed: data did not match any variant of untagged enum SchemaType at line 88 column 5`. The issue is that `context` cannot be mapped to an empty `{}`: If present you need to give it a `"type": "Record"` etc.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by john-h-kastner-aws** [comment]
Errors two and four are already fixed. For point two it still prints JSON, but this is desirable IMO because that's what the user types in the schema (unless we want to create that non-json schema format :) ).

Error one can be improved easily.

Error three relates to a broader class of poor errors our parsers. I ideally we could improve all of them at once. Regarding line numbers for schema parsing errors. There's no clear way to capture line numbers when using serde to parse JSON into our schema "CST". Adding line numbers to schema errors would be a large rework of the schema parsing code.

**Comment by john-h-kastner-aws** [comment]
I looked into getting at the source locations a bit and found this: https://github.com/serde-rs/json/issues/637

It definitely looks likes it's possible. There's a crate linked that does something like what we want. It's not quite exactly what we need, but the implementation shows how we could do this ourselves.

**Comment by john-h-kastner-aws** [comment]
Closing in favor of #174 #175 #176
