### ISSUE TITLE
`cedar-policy` crate should fix the versions of `cedar-policy-core` and `cedar-policy-validator` it depends on

### ISSUE THREAD

**Issue by cdisselkoen** [cedar-policy/cedar#153]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Other

### Describe the bug

Currently, `cedar-policy` uses the implicit `^` dependency for Core and Validator.  This means that, e.g., `cedar-policy` 2.2 will accept Core and Validator 2.3 as compatible.  Unfortunately, since we don't currently follow semver for Core and Validator (only for `cedar-policy`), this could result in build problems or other breakage if Cargo actually tries to give Core/Validator 2.3 to `cedar-policy` 2.2 -- e.g., because someone tries to depend on `cedar-policy` `"=2.2"` in their `Cargo.toml`.  To prevent this, we should change the `Cargo.toml` of `cedar-policy` to use the `=` constraint in its dependencies on Core and Validator.  Probably also the same change in Validator's `Cargo.toml` for its Core dependency.

**Comment by cdisselkoen** [comment]
Commenting that I think this change should be backported to 2.0, 2.1, 2.2, and 2.3, in addition to `main`

**Comment by cdisselkoen** [comment]
(and probably patch releases of each of those)

**Comment by cdisselkoen** [comment]
Reopening this until backports are complete -- at a minimum we should backport to 2.3.x

**Comment by aaronjeline** [comment]
TODO
- [ ] 2.3.x
- [ ] 2.2.x 
- [ ] 2.1.x 
- [ ] 2.0.x

**Comment by aaronjeline** [comment]
https://github.com/cedar-policy/cedar/pull/161

**Comment by aaronjeline** [comment]
2.1.x: https://github.com/cedar-policy/cedar/pull/162

**Comment by aaronjeline** [comment]
2.2.x: https://github.com/cedar-policy/cedar/pull/163

**Comment by aaronjeline** [comment]
2.3.x: https://github.com/cedar-policy/cedar/pull/164
