### ISSUE TITLE
Support permissive-mode validation in the CLI

### ISSUE THREAD

**Issue by mwhicks1** [cedar-policy/cedar#156]
### Category

Other

### Describe the feature you'd like to request

The CLI always calls the validator in the default (strict) mode. I'd like to add a command-line flag to allow permissive mode.

### Describe the solution you'd like

Extending `lib.rs` in the `cedar-policy-cli` directory to support an additional validation flag.

### Describe alternatives you've considered

The only alternative is not to allow calling permissive mode from the CLI at all, but this seems weird since we support it in the library APIs

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by memark** [comment]
I have now implemented this using my second suggestion above.
