### ISSUE TITLE
Suggested replacement for unrecognized action entity misses obvious fix

### ISSUE THREAD

**Issue by mwhicks1** [cedar-policy/cedar#166]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Schemas and Validation

### Describe the bug

The `actions` section of the schema lists entity IDs, whereas the `entityTypes` section lists entity types. If a user mistakenly includes the `Action` entity type (and any namespace) as part of their action ID, the error messages are confusing. 

### Expected behavior

Ideally, the error message can identify the user's mistake more clearly, and do better at suggesting a fix. The suggestion would need to account for this particular mistake of including part of the type/namespace in the action ID.

### Reproduction steps

In [tinytodo's `tinytodo.cedarschema.json`](https://github.com/cedar-policy/cedar-examples/blob/main/tinytodo/tinytodo.cedarschema.json), modify the `actions` element `"createList"` to instead be `"Action::CreateList"`. When validating `polices.cedar` we get the error message
```
Validation error on policy policy0: Unrecognized action id Action::"CreateList", did you mean Action::"GetList"?
```
This is confusing! With this change, we are defining an action entity `Action::"Action::CreateList"`. This is not what the user intended, because they failed to appreciate the distinction between entity IDs and entity types.

**Comment by adpaco-aws** [comment]
I haven't been able to reproduce this issue yet.

First, the JSON file [tinytodo.cedarschema.json](https://github.com/cedar-policy/cedar-examples/blob/main/tinytodo/tinytodo.cedarschema.json) doesn't exist anymore, and has been replaced by the non-JSON schema since then. It's possible to retrieve the file going to the 3.0 branch:  [release/3.0.x/tinytodo.cedarschema.json](https://github.com/cedar-policy/cedar-examples/blob/release/3.0.x/tinytodo/tinytodo.cedarschema.json). My fork now includes the [issue-166 branch](https://github.com/adpaco-aws/cedar-examples/tree/issue-166) which uses the JSON schema, but results in the following parsing error:
```
>>>   2024-09-09T23:33:18.014524Z ERROR tiny_todo_server: Failed to load entities, policies, or schema: Error Parsing Human-readable Schema: error parsing schema: unexpected token `{`
```

**Comment by john-h-kastner-aws** [comment]
When looking at these error messages, you should be aware that tiny-todo might not be printing all available information (cedar-policy/cedar-examples#97). The CLI will do better job of it, but we've previously noted that it may be dropping source information for some schema parsing errors (#948). Both of these should be pretty simple fixes if you want to knock them out.

**Comment by john-h-kastner-aws** [comment]
Also, while looking at this code, it might make sense resolve #246, #332, and #380 at the same time since these all deal with the suggested replacement mechanism.
