### ISSUE TITLE
[Cedar 3.0] Remove deprecated features

### ISSUE THREAD

**Issue by khieta** [cedar-policy/cedar#180]
### Category

User level API changes

### Describe the feature you'd like to request

We have one API and one language feature that are commented as being deprecated. We should consider removing them from the code base in the next major release.
* The `EntityUid::from_str()` API has been deprecated since version 1.2 [[link](https://github.com/cedar-policy/cedar/blob/12bd8594dca61361cd6bba9d759bddb8913d4cf4/cedar-policy/src/api.rs#L1095)]
* The `__expr` syntax for specifying Cedar expressions in JSON has been deprecated since version 1.2.

### Describe the solution you'd like

Remove the code corresponding to the features above. Removing `EntityUid::from_str()` should be quick. Removing references to `__expr` will be more involved. It will also require updating our integration tests, which still use this syntax.

### Describe alternatives you've considered

N/A

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [X] ⚠️ This feature might incur a breaking change

**Comment by khieta** [comment]
Made a separate issue for updating the integration tests #181

**Comment by cdisselkoen** [comment]
Removing `EntityUid::from_str()` may not be trivial, as the CLI uses it for the `--principal`, `--action`, etc arguments.  The CLI arguments will probably have to be specified in a different format.

**Comment by cdisselkoen** [comment]
Closed by #319 and #333
