### ISSUE TITLE
Update integration tests to remove `__expr` syntax

### ISSUE THREAD

**Issue by khieta** [cedar-policy/cedar#181]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Other

### Describe the bug

The `__expr` syntax for writing Cedar expressions in JSON has been marked as deprecated since version 1.2 (see comment [here](https://github.com/cedar-policy/cedar/blob/12bd8594dca61361cd6bba9d759bddb8913d4cf4/cedar-policy-core/src/entities/json/jsonvalue.rs#L47)). The preference is to use `__entity` or `__extn` instead. Our integration tests (in [cedar-integration-tests/sample-data](https://github.com/cedar-policy/cedar/tree/main/cedar-integration-tests/sample-data)) still use `__expr` -- we should fix this so users don't mistakenly think that this is the preferred syntax.

### Expected behavior

N/A

### Reproduction steps

N/A

**Comment by andrewmwells-amazon** [comment]
Closed in https://github.com/cedar-policy/cedar/pull/235
