### ISSUE TITLE
Split `ParseError` into more descriptive enum variants

### ISSUE THREAD

**Issue by cdisselkoen** [cedar-policy/cedar#183]
### Category

User level API changes

### Describe the feature you'd like to request

Today, `ParseError` has only a few variants, and involves strings.  We should have more descriptive variants for our parse errors, in line with how our other error enums work.

### Describe the solution you'd like

More variants of `ParseError`, or secondary structs like a `CstToAstError` or whatever, that have descriptive names / doc strings / etc.

### Describe alternatives you've considered

N/A

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [X] ⚠️ This feature might incur a breaking change

**Comment by anwarmamat** [comment]
Closed by #243
