### ISSUE TITLE
api.rs: Distinguish types for static and linked policies

### ISSUE THREAD

**Issue by cdisselkoen** [cedar-policy/cedar#189]
### Category

User level API changes

### Describe the feature you'd like to request

Right now the `Policy` object represents both static and linked policies.  Whether we keep `Policy` or not, we should have specific types for static and linked policies, so that e.g. we can expect the appropriate type in `PolicySet::add()`. The goal is also to eliminate the `PolicySetError::ExpectedStatic` error variant.

### Describe the solution you'd like

As above.

### Describe alternatives you've considered

Possibly this won't work or will add too much complexity to our API

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [X] ⚠️ This feature might incur a breaking change

**Comment by mstalzer** [comment]
We've decided it's not worth the breaking change. We can revisit if there is future demand.
