### ISSUE TITLE
Improvements to ExtensionsError variants representing internal invariant violations

### ISSUE THREAD

**Issue by cdisselkoen** [cedar-policy/cedar#193]
### Category

User level API changes

### Describe the feature you'd like to request

Several variants of `ExtensionsError` -- `HasNoType`, `FuncMultiplyDefined`, and `MultipleConstructorsSameSignature` -- represent internal invariant violations more than they represent something the user did wrong.  In the current world where we control all the language extensions, these should never be thrown, and if they are thrown, it represents a bug in our code.

We should mark these as internal errors -- perhaps by making a struct `InternalError` (or some other name) and having that be a variant of `ExtensionsError`.  If possible, we should also reorganize `ExtensionsError` and/or `EvaluationError` so that these errors are (a) caught as early as possible, eg before `is_authorized()`, and (b) not part of `EvaluationError`, so that consumers of `EvaluationError` don't have to worry about matching on these.

We want to catch these as early as possible, but we also don't want to do unnecessary expensive checks on the hot path.  One option is to do it when constructing an `Extensions` object, if that is not on the hot path or can be moved off the hot path.

### Describe the solution you'd like

As above.

### Describe alternatives you've considered

Removing these variants entirely in favor of some other mechanism or refactor that makes those errors impossible.  This might be very difficult without restructuring our extensions mechanism.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cdisselkoen** [comment]
If we're going to do this, we should do this before 4.0 so it can be batched with all of the #745 changes.

**Comment by john-h-kastner-aws** [comment]
Also look at the corresponding errors in the validator

**Comment by john-h-kastner-aws** [comment]
I was looking into this and found that passing an incorrect number of arguments to a extension function or method only errors at evaluation and not in parsing.

```bash
cargo run check-parse <<< 'permit(principal, action, resource) when { 1.isInRange(0, 1) };'
```

This is unfortunate since we could easily detect this immediately on parsing, but changing this is potentially disruptive.

**Comment by cdisselkoen** [comment]
Possibly related: #85 (as of this writing our second-oldest open issue)
