### ISSUE TITLE
Update docstrings and add examples

### ISSUE THREAD

**Issue by cdisselkoen** [cedar-policy/cedar#205]
### Category

Other

### Describe the feature you'd like to request

We should do a full audit of all of our docstrings visible in the public documentation at [docs.rs/cedar-policy](https://docs.rs/cedar-policy). 

While we're at it, we should add short examples of API usage in the docstrings, for functions/methods where that makes sense.  These will be doctests as well.

### Describe alternatives you've considered

N/A

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by john-h-kastner-aws** [comment]
Calling this done. Open a new issue for specific doc improvements
