### ISSUE TITLE
Eagerly compute values in entities slice object rather than with every call to `is_authorized`

### ISSUE THREAD

**Issue by aaronjeline** [cedar-policy/cedar#227]
### Category

Internal refactors/changes

### Describe the feature you'd like to request

Currently, the entities slice object maps EUIDs to restricted expressions, and the authorizor evaluates these to values at the beginning of every call to `is_authorized`
Instead, we would like it to map EUIDs to values, so that this computation can be amortized across all calls to `is_authorized`

### Describe alternatives you've considered

Alternatives would be genericizing the entity slice, which is a more complicated lift

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by andrewmwells-amazon** [comment]
Might be worth mentioning lazy, cached evaluation as an alternative? (Also I renamed the issue to make it clear that the current computation is eager, but is done per `is_authorized`)

**Comment by cdisselkoen** [comment]
This is also discussed in cedar-policy/rfcs#16

**Comment by cdisselkoen** [comment]
and now in cedar-policy/rfcs#28

**Comment by cdisselkoen** [comment]
Closed in favor of [RFC 34](https://github.com/cedar-policy/rfcs/pull/34)
