### ISSUE TITLE
Rewrite the policy formatter based on ESTs

### ISSUE THREAD

**Issue by shaobo-he-aws** [cedar-policy/cedar#239]
### Category

Internal refactors/changes

### Describe the feature you'd like to request

EST should be the representation the policy formatter works on. CSTs are too permissive, which results in a large amount of deconstruction of `Option`s.

### Describe alternatives you've considered

Keep status quo.

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by anwarmamat** [comment]
EST currently does not support comments, but the policy formatter has to keep the comments. How does the formatter work with ETS?

**Comment by shaobo-he-aws** [comment]
> EST currently does not support comments, but the policy formatter has to keep the comments. How does the formatter work with ETS?

The formatter doesn't rely on tree nodes to contain comments. Instead, it requires them to contain precise source location information.

**Comment by shaobo-he-aws** [comment]
Closed this issue since EST do not contain source loc info.
