### ISSUE TITLE
Fuzzy matching on unknown method error message

### ISSUE THREAD

**Issue by aaronjeline** [cedar-policy/cedar#246]
### Category

Other

### Describe the feature you'd like to request

The function `ast::Id::to_meth` errors if the underlying `Id` doesn't name a method. It would be useful to fuzzy match the `Id` against all the possible methods to provide the user with guesses as to what they may have met

### Describe alternatives you've considered

Leave error message as is

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by andrewmwells-amazon** [comment]
It may be worth considering a more general "add suggestions for typos" to error messages. E.g., the ones mentioned in this comment: https://github.com/cedar-policy/cedar/pull/222#discussion_r1278119832
