### ISSUE TITLE
Better error message for dashes in identifiers

### ISSUE THREAD

**Issue by khieta** [cedar-policy/cedar#255]
### Category

Cedar syntax changes/additions

### Describe the feature you'd like to request

Cedar identifiers (e.g., names in namespaces) can use the character set `[A-Za-z0-9_]`. These are all the characters you would expect to see in a variable name, except perhaps `-`. If an identifier includes a dash, then this can lead to potentially confusing error messages because that character will be parsed as subtraction.

Example:
```
permit (
    principal == name-with-dashes::"Alice",
    action,
    resource
);
```
Produces the error message "poorly formed: expected a entity uid or template slot, found a `+/-` statement".

It would be more helpful if it produced an error message like: "invalid identifier: name-with-dashes".

### Describe alternatives you've considered

N/A

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by khieta** [comment]
Note: this is likely not a simple fix because it requires changing our definition of an identifier in the parser.

**Comment by cdisselkoen** [comment]
It might not require changing the definition of identifier in the parser, if we can identify this error case (which probably looks like, subtraction with identifiers or names on both sides, or something like that) in the current CST and provide an appropriate error message
