### ISSUE TITLE
Provide a mechanism for creating an `Entity` from JSON

### ISSUE THREAD

**Issue by aaronjeline** [cedar-policy/cedar#275]
### Category

User level API changes

### Describe the feature you'd like to request

Provide a mechanism for creating a single `Entity` from JSON. Currently it is only possible to create the full `Entities` structure.

### Describe alternatives you've considered

See #272 

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by john-h-kastner-aws** [comment]
Closing as completed by #924
