### ISSUE TITLE
Nested action groups don't work properly in schema-based parsing

### ISSUE THREAD

**Issue by cdisselkoen** [cedar-policy/cedar#285]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Policy Evaluation

### Describe the bug

When you include actions both in the schema and in the entities passed to schema-based parsing, Cedar ensures the definition of each action agrees across the two sources.  However, this check is done _after_ computing TC for the schema actions but _before_ computing TC for the entities' actions, meaning that in order to pass this check, the caller has to precompute TC manually for their actions, even if they pass `TCComputation::ComputeNow`.  Instead, the check for agreement of action definitions should be done after the TC computation in both cases.

### Expected behavior

When you pass the same actions to the schema-based entity JSON parser as appear in the schema, this should work properly, even in the presence of nested action groups, without having to manually compute TC in either place.

### Reproduction steps

1. Create a schema with nested action groups (e.g. action 1 -> action 2 -> action 3)
2. Try to construct an `Entities` using schema-based JSON parsing, which includes the actions in the same non-TC form as they appeared in the schema
3. Observe the error `definition of action [X] does not match its schema declaration`

**Comment by khieta** [comment]
Resolved by #581
