### ISSUE TITLE
Support new type 'map' in schema definition

### ISSUE THREAD

**Issue by cplee** [cedar-policy/cedar#305]
### Category

Cedar validation features

### Describe the feature you'd like to request

I would like to be able to define a 'map' type in my schema:

```
{
  "MyNamespace": {
    "commonTypes": {
      "MyMap": { "type": "Map", "keys": "String", "values": "String" }
    }
}
```

This would allow me to pass entities with values like:

```
...
   "foo": {
      "alice": "tall",
      "bob": "short"
   }
...
```

And then have policy like:

```
  principal.foo has "alice" && principal.foo.alice == "tall"
```

### Describe alternatives you've considered

Converting to a `Set` with a record of attributes `Key` and `Value`. This doesn't allow me to use operations like `has` or easily find the `Value`.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by anwarmamat** [comment]
Current schema format supports records and nested records. For example:
```
"commonTypes": {
    "ReusedContext": {
        "type": "Record",
        "attributes": {
            "ip": { "type": "Extension", "name": "ipaddr" },
            "is_authenticated": { "type": "Boolean" },
            "timestamp": { "type": "Long" }
        }
    }
}
```

Did you try records?

**Comment by cdisselkoen** [comment]
In response to @anwarmamat's comment above -- today's records do not fully support the use case described above, because you cannot ascribe types to record fields without explicitly listing the record fields in the schema.  In the use-case above, the user wants to ascribe a type (`String`) to all fields, without explicitly listing the fields or guaranteeing their existence.

**Comment by aaronjeline** [comment]
If we want to move forward with this issue, I think it would be best if we added it as an RFC. If you're still interested in adding maps to the language, would you be interested in drafting an RFC proposal? (See: https://github.com/cedar-policy/rfcs)

**Comment by cdisselkoen** [comment]
Closed in favor of [RFC 27](https://github.com/cedar-policy/rfcs/pull/27)
