### ISSUE TITLE
Stricter validation of action.appliesTo in schema.

### ISSUE THREAD

**Issue by max2me** [cedar-policy/cedar#306]
### Category

Cedar validation features

### Describe the feature you'd like to request

Today attributes of appliesTo are validated independently of each other leading to situation where `principalTypes` could be `[]` (making action inelegible for being part of authz request) while `resourceTypes` might specify mulitple entity types, or even all of them. Additionally, in this situation context shape becomes irrelevant.

Feature request:  
Additional validation to ensure consistency of appliesTo parameters: If either `resourceType` or `principalType` are set to `[]`, then require the other one to be also set to `[]` and have context be undefined.

### Describe alternatives you've considered

Doing this validation on the client in the UI.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [X] ⚠️ This feature might incur a breaking change

**Comment by cdisselkoen** [comment]
Superseded by [RFC 35](https://github.com/cedar-policy/rfcs/pull/35)
