### ISSUE TITLE
Schema: add an explicit way to specify that action applies to all principal/resource types

### ISSUE THREAD

**Issue by max2me** [cedar-policy/cedar#320]
### Category

Cedar validation features

### Describe the feature you'd like to request

Today, if user wants to define that action applies to all principal types or resource types, they can either omit `action.appliesTo.principalTypes` / `action.appliesTo.resourceTypes` or they can omit `action.appliesTo` entirely if action does not depend on context.

While this is a very concise way of providing specifications, it also introduces the risk of user unknowingly defining an action group that also, as an action, applies to types.

Feature ask: add an explicit way of specifying that action applies to all entity types, such as using `["*"] in appliesTo block:
```
"create": {
   "appliesTo":  {
      "principalTypes": ["User"],
      "resourceTypes": ["*"]
   }
}
```

Tooling then can take advantage of this feature by prompting users to convert definition of actions that apply to all types to use explicit method. This will help ensure that schema is aligned with customers intent.

### Describe alternatives you've considered

* Not doing this feature
* Introducing additional property such as `"allPrincipalTypes": true`

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by emina** [comment]
I would vote against providing a shorthand (such as `[*]`) for specifying that an action can apply to _all_ types.  In general, we want to encourage users to minimize the applicability / scope of their actions, for understandability, security, and efficiency of validation.  It's safest to explicitly specify (enumerate) the set of types to which an action applies.

I agree that we do want to provide some syntax for saying that the principal or resource type is "unspecified" (or "don't care").  The unspecified type is disjoint from all other types and has no attributes.  [RFC 19](https://github.com/cedar-policy/rfcs/blob/main/text/0019-stricter-validation.md#unspecified-principalresource-entity-types) has the details.

**Comment by mwhicks1** [comment]
I've updated the RFC to address this request.
