### ISSUE TITLE
 `Display for ParseErrors` in version 2.4 only shows the first error

### ISSUE THREAD

**Issue by anwarmamat** [cedar-policy/cedar#326]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Cedar Parser

### Describe the bug

In 2.3.3, if we try to parse the policy `permit(principal        action          resource );`  using `PolicySet::from_str`, it prints the following error: 
```
Unrecognized token `action` found at 39:45
Expected one of "!=", ")", ",", ":", "<", "<=", "==", ">", ">=" or IN
  Unrecognized token `resource` found at 55:63
Expected one of "("
  Unrecognized token `)` found at 68:69
Expected one of "("
```

But, in 2.4, it only prints
```
unexpected token `action`
```
although the debug print include all errors:
```
ParseErrors([
ToCST(ToCSTError { err: UnrecognizedToken { token: (39, "action", 45), expected: ["\"!=\"", "\")\"", "\",\"", "\":\"", "\"<\"", "\"<=\"", "\"==\"", "\">\"", "\">=\"", "IN"] } }), 
ToCST(ToCSTError { err: UnrecognizedToken { token: (55, "resource", 63), expected: ["\"(\""] } }), 
ToCST(ToCSTError { err: UnrecognizedToken { token: (68, ")", 69), expected: ["\"(\""] } })])
unexpected token `action`
```

Here is the `Display` code for 2.3.3 and 2.4

In 2.3.3
```
impl std::fmt::Display for ParseErrors {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", MultipleParseErrors(&self.0))
    }
}
```
In 2.4
```
impl Display for ParseErrors {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.first() {
            Some(first_err) => Display::fmt(first_err, f),
            None => write!(f, "{}", Self::DESCRIPTION_IF_EMPTY),
        }
    }
```
}

### Expected behavior

The `Display` method should print all the error and source locations

### Reproduction steps

Run the code snippet below

### Code Snippet

```rust
let src = r#"
    permit(
        principal
        action 
        resource
    );
    
"#;
    let p = PolicySet::from_str(src);
    match p {
        Ok(pset) => {
           ...
        }
        Err(e) => {
            println!("{}", e)
        }
    }
```

### Log output

```
// Put your output below this line

```

### Operating  System

Linux

**Comment by spinda** [comment]
FYI, I'm no longer at AWS, but I'll still be handling this. Will have a patch in this week.

**Comment by cdisselkoen** [comment]
Looking at this again.  I'm genuinely not sure which behavior we want.  Compare the following `miette` output with all the error messages in `Display`:
```
Error:   × failed to parse policy set
  ╰─▶ multiple parse errors: unexpected token `action`; unexpected token `resource`; unexpected token `)`

Error: cedar_policy_core::parser::to_cst_error

  × unexpected token `action`
   ╭─[bad_policies.cedar:1:1]
 1 │ permit ( principal    action       resource );
   ·                       ───┬──
   ·                          ╰── expected `!=`, `)`, `,`, `:`, `<`, `<=`, `==`, `>`, `>=`, `in`, or `is`
   ╰────
Error: cedar_policy_core::parser::to_cst_error

  × unexpected token `resource`
   ╭─[bad_policies.cedar:1:1]
 1 │ permit ( principal    action       resource );
   ·                                    ────┬───
   ·                                        ╰── expected `(`
   ╰────
Error: cedar_policy_core::parser::to_cst_error

  × unexpected token `)`
   ╭─[bad_policies.cedar:1:1]
 1 │ permit ( principal    action       resource );
   ·                                             ┬
   ·                                             ╰── expected `(`
   ╰────

```
vs the output with just the first error message in `Display`:
```
Error:   × failed to parse policy set
  ╰─▶ unexpected token `action`

Error: cedar_policy_core::parser::to_cst_error

  × unexpected token `action`
   ╭─[bad_policies.cedar:1:1]
 1 │ permit ( principal    action       resource );
   ·                       ───┬──
   ·                          ╰── expected `!=`, `)`, `,`, `:`, `<`, `<=`, `==`, `>`, `>=`, `in`, or `is`
   ╰────
Error: cedar_policy_core::parser::to_cst_error

  × unexpected token `resource`
   ╭─[bad_policies.cedar:1:1]
 1 │ permit ( principal    action       resource );
   ·                                    ────┬───
   ·                                        ╰── expected `(`
   ╰────
Error: cedar_policy_core::parser::to_cst_error

  × unexpected token `)`
   ╭─[bad_policies.cedar:1:1]
 1 │ permit ( principal    action       resource );
   ·                                             ┬
   ·                                             ╰── expected `(`
   ╰────
```
(Note the difference at the top of the respective outputs.) The latter (with only the first error message in `Display`) might be more sensible and cleaner. 

This is especially true in more complicated cases where the parse errors are not just three words (as above) but are themselves long and containing internal `;` or `:`.  For example, for the policy
```
permit ( principal == App-User::"a", action, resource in Group::"A" is R ) onlywhen { true };
```
if we put all the error messages in `Display`, we get:
```
Error:   × failed to parse policy set
  ╰─▶ multiple parse errors: expected an entity uid or matching template slot, found a `+/-` expression; note that
      entity types and namespaces cannot use `+` or `-` characters -- perhaps try `_` or `::` instead?; expected
      an entity uid or matching template slot, found an `is` expression; not a valid policy condition: `onlywhen`.
      Condition must be either `when` or `unless`

Error: cedar_policy_core::parser::to_ast_err

  × expected an entity uid or matching template slot, found a `+/-` expression; note that entity types and
  │ namespaces cannot use `+` or `-` characters -- perhaps try `_` or `::` instead?
Error: cedar_policy_core::parser::to_ast_err

  × expected an entity uid or matching template slot, found an `is` expression
Error: cedar_policy_core::parser::to_ast_err

  × not a valid policy condition: `onlywhen`. Condition must be either `when` or `unless`
```
That first block is a mess and not a good user experience IMO.

Another option is to have _none_ of the specific error messages in `Display` (at least in the multiple-error case) and just something like "multiple parse errors; see below".  This is based on the observation that including any of the error messages in the `Display` is redundant in `miette`'s output.  However, it's a very bad experience for users just using `Display` and unaware of `miette`, so for that reason I don't suggest this option.

I'm leaning towards the status quo, with just the first error message in `Display`, and all of the error messages available in the pretty `miette` output or programmatically using `miette`.

**Comment by cdisselkoen** [comment]
here's another prototype. This is if we remove the "error code" `cedar_policy_core::parser::to_ast_err`; move some of the error text into `miette`'s `help`; and put all the error messages in `Display`.
```
Error:   × failed to parse policy set
  ╰─▶ multiple parse errors: expected an entity uid or matching template slot, found a `+/-` expression; expected an
      entity uid or matching template slot, found an `is` expression; not a valid policy condition: `onlywhen`

Error:   × expected an entity uid or matching template slot, found a `+/-` expression
  help: entity types and namespaces cannot use `+` or `-` characters -- perhaps try `_` or `::` instead?
Error:   × expected an entity uid or matching template slot, found an `is` expression
Error:   × not a valid policy condition: `onlywhen`
  help: condition must be either `when` or `unless`

```
Since the actual error messages are somewhat more concise, the top block doesn't look so disastrous with the `;` separator.  On the other hand, if the point was to provide more information to users who only use `Display` and aren't aware of `miette`, then those users now have no way to get the help text at all.  Is it better to have the `Display` text have multiple errors but no help text, or a single error with its help text?  

If we maximize for `miette` prettiness, we probably have single error (or no errors) in `Display` and just use the `miette` features to list the detailed error messages and help text.

**Comment by shaobo-he-aws** [comment]
I wonder if the implementation of the `Display` trait shouldn't be responsible for pretty-printing (i.e., decoupled from `miette`). We just print the error messages separated by newlines.

**Comment by cdisselkoen** [comment]
Unfortunately, `miette` seems to use the `Display` trait itself for these messages, so I don't think we can decouple

**Comment by cdisselkoen** [comment]
(also note that the missing source information in the errors in that last example is a different issue -- #465)

**Comment by cdisselkoen** [comment]
Based on this and additional offline conversation, I'm going to close this.  After #182, our users should hopefully be oriented to `miette` and comfortable with its output, and we will mostly optimize for that.  We will still be careful to keep the `Display` output reasonably helpful, but we'll be removing things like `help` and source location from the `Display` in favor of `miette`'s other structured fields.  In line with that, putting only the first error message in the `Display` makes sense.  (But, putting only a note like "multiple errors, see below" in the `Display` would not be helpful and we will not be doing that.)

Everyone should feel free to continue the discussion here if they want.  (And also to reopen this issue if you disagree with closing it.)
