### ISSUE TITLE
Provide remove methods for PolicySet

### ISSUE THREAD

**Issue by 0x00A5** [cedar-policy/cedar#328]
### Category

User level API changes

### Describe the feature you'd like to request

The `PolicySet` struct provides `add`, `add_template`, `link` methods to insert static policy, policy template and dynamic policy to a policy set. It would be useful to also provide the counterpart methods to remove these policies from a policy set.

```rust
/// Remove a static policy from the policy set
fn remove(&mut self, policy_id: PolicyId) -> Result<(), PolicySetError>;

/// Remove a policy template and all dynamic policies linked to it
fn remove_template(&mut self, template_id: PolicyId) -> Result<(), PolicySetError>;

/// Unlink a dynamic policy from the policy set
fn unlink(&mut self, policy_id: PolicyId) -> Result<(), PolicySetError>;
```

### Describe alternatives you've considered

Alternatively, these methods could be replaced by a simple `remove` method that takes a policy id and according to the policy type, removes the policy/template or unlink the dynamic policy.

### Is this something that you'd be interested in working on?

- [x] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by andrewmwells-amazon** [comment]
Closed with https://github.com/cedar-policy/cedar/pull/337
