### ISSUE TITLE
Remove atty dependency

### ISSUE THREAD

**Issue by andrewmwells-amazon** [cedar-policy/cedar#33]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+) and [discussions](https://github.com/cedar-policy/cedar/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Other

### Describe the bug

Our (transitive, through criterion) atty dependency is outdated. The version used has a security vulnerability. We aren't exposed to it but once a new version of criterion is released we should upgrade so we don't have the transitive atty dependency.

**Comment by john-h-kastner-aws** [comment]
For reference https://github.com/bheisler/criterion.rs/pull/628 updated the dependency in criterion. Comments by a maintainer at the end of that thread indicate that we can expect a release on a reasonable timeline.
