### ISSUE TITLE
Add partial evaluation to the CLI

### ISSUE THREAD

**Issue by aaronjeline** [cedar-policy/cedar#331]
### Category

Other

### Describe the feature you'd like to request

The cedar CLI should let you experiment with partial evaluation queries.

### Describe alternatives you've considered

Not doing this

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cdisselkoen** [comment]
Among the outputs, it should allow you to see the residuals in human format, in JSON format, and as a flat list of the `.unknowns()` in the residuals.

**Comment by shaobo-he-aws** [comment]
> Among the outputs, it should allow you to see the residuals in human format, in JSON format, and as a flat list of the `.unknowns()` in the residuals.

I'm planning to work on it. What does `a flat list of unknowns` mean?

**Comment by cdisselkoen** [comment]
I think when I wrote that I meant "just a list of the unknowns contained in the expression, without the rest of the structure of the expression"

**Comment by shaobo-he-aws** [comment]
> I think when I wrote that I meant "just a list of the unknowns contained in the expression, without the rest of the structure of the expression"

I'm not sure if it's helpful. What is the usage of the list of unknowns?

**Comment by cdisselkoen** [comment]
So you know which entities need fetching?

**Comment by cdisselkoen** [comment]
You probably know better than me if there is something else that better supports the use case of "I partial evaluate providing only the request/entity data that is cheap to fetch/compute, and then I look at the returned residuals to determine what other data I need in order to get a complete authorization decision"

**Comment by shaobo-he-aws** [comment]
> You probably know better than me if there is something else that better supports the use case of "I partial evaluate providing only the request/entity data that is cheap to fetch/compute, and then I look at the returned residuals to determine what other data I need in order to get a complete authorization decision"

I see. It's just that PE doesn't "fully" evaluate the expression so there could be implicit unknowns. For instance, we'll have a residual like `unknown("principal.a") || principal.b` for expression `principal.a || principal.b`, where `a` and `b` are both unknowns.

**Comment by john-h-kastner-aws** [comment]
Added by #1082
