### ISSUE TITLE
Validation error messages expose too much implementation detail

### ISSUE THREAD

**Issue by shaobo-he-aws** [cedar-policy/cedar#346]
### Category

Cedar validation features

### Describe the feature you'd like to request

Consider the example policy,

```
// Everyone in the group UserGroup::"jane_friends" can view this specific photo
@id("jane's friends view-permission policy")
permit (
  principal in UserGroup::"jane_friends",
  action == Action::"view",
  resource == Photo::"VacationPhoto94.jpg"
) when {
  [UserGroup::"jane_friends"].contains(Photo::"VacationPhoto94.jpg")
};
```

The validator reports,
```
Validation Results:
validation error on policy `jane\'s friends view-permission policy` at offset 258-324: unable to find upper bound for types: [{"type":"Entity","name":"Photo"},{"type":"Entity","name":"UserGroup"}]
```

Upper bound for entity types seem cryptic to users.

### Describe alternatives you've considered

We should produce more user-friendly explanation.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by khieta** [comment]
+1 to this issue. Proposal for new wording: `incompatible types: <type 1> and <type 2>`, with context-specific help messages like the following:
* `both branches of an if-then-else must have the same type`
* `both sides of an equality must have the same type`
* `sets must contain elements of the same type`
