### ISSUE TITLE
implement RestrictedExpression::new_entity_uid() (or similar)

### ISSUE THREAD

**Issue by verrchu** [cedar-policy/cedar#350]
### Category

User level API changes

### Describe the feature you'd like to request

I want to be able to "manually" create entities which refer to other entities

my use case:

I have two entities defined in my policy schema file
```
        "entityTypes": {
            "Client": {
                "shape": {
                    "type" : "Record",
                    "attributes" : {
                        "id": { "type": "String" }
                    }
                }
            },
            "User": {
                "memberOfTypes": ["Role"],
                "shape": {
                    "type" : "Record",
                    "attributes" : {
                        "id": { "type": "String" },
                        "client": { "type": "Entity", "name": "Client" }
                    }
                }
            },
```

then I create user entity like this

```
        let attrs = HashMap::from_iter([
            (
                "id".to_string(),
                RestrictedExpression::new_string(self.id.to_string()),
            ),
            // FIXME: we are building a `record` here while the type of
            // "client" here is really `Entity`. This seems to work but
            // need to confirm further on `cedar` slack
            (
                "client".to_string(),
                RestrictedExpression::new_record([(
                    "id".to_string(),
                    RestrictedExpression::new_string(self.client.id.to_string()),
                )]),
            ),
        ]);

        let user_entity = Entity::new(uid, attrs, parents);
```

note that I use `new_record` method to create an entity (and it works!)

### Describe alternatives you've considered

an alternative with using `new_record` (which probably shouldn't work) is described above

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by khieta** [comment]
(Sorry for the delayed response.) Thanks for the suggestion, we agree that would be useful! We've added it to our backlog for now, but we also marked it as "good first issue" since this is a small API change that we would love a PR for 😉
