### ISSUE TITLE
JSON `is_authorized` API silently ignored duplicate template slot values

### ISSUE THREAD

**Issue by jamiewinder** [cedar-policy/cedar#352]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Cedar Parser

### Describe the bug

I'm using Cedar through the JSON API (`json_is_authorized`). I'm not sure if the normal API is affected.

This is an example request:
```json
{
        "principal":"User::\"1\"",
        "action":"Action::\"View\"",
        "resource":"Document::\"123\"",
        "context":{},
        "schema":null,
        "slice":{
           "entities":[],
           "policies": {},
           "templates":{
              "test_template":"permit(\r\n  principal in ?principal, \r\n  action, \r\n  resource\r\n);"
           },
           "template_instantiations":[
              {
                 "template_id":"test_template",
                 "result_policy_id":"test_template_result",
                 "instantiations":[
                    {
                       "slot":"?principal",
                       "value":{
                          "ty":"User",
                          "eid":"2"
                       }
                    },
                    {
                       "slot":"?principal",
                       "value":{
                          "ty":"User",
                          "eid":"1"
                       }
                    }
                 ]
              }
           ]
        }
     }
```
The result of this is Allow. Note there are two `template_instantiations`. If these are swapped around, the result becomes Deny.

It appears the last template instantiation overwrites any previous ones?

### Expected behavior

Multiple template instantiations should not overwrite each other.

### Reproduction steps

Include multiple template instantiations.

### Log output

```
// Put your output below this line

```

### Operating  System

Windows

**Comment by andrewmwells-amazon** [comment]
Thanks for the issue report. I think the current behavior is intentional but confusing; As you noted, we take the last instantiation. This matches how we handle duplicate record keys (https://github.com/cedar-policy/rfcs/blob/main/text/0020-unique-record-keys.md). We'll look into changing this because the current behavior is confusing and it's unclear when it would be desired.

**Comment by jamiewinder** [comment]
Thanks for your reply. I'd assume this behaviour isn't found in the non-JSON API? 

I'm creating .NET bindings for Cedar following the same approach as the Java ones (based on the JSON API) and it would seem that for both will be affected by this behaviour which means policy templates cannot be used.

Hopefully this can be sorted without too much upset. Thanks again!

**Comment by andrewmwells-amazon** [comment]
Actually, someone pointed out to me you may have intended to instantiate the template twice. In that case you'd need distinct `result_policy_id`s for each instantiated policy. Something like:
```
template_instantiations:[
  {
    "template_id": "test_template",
    "result_policy_id": "test_template_result1",
    "instantiations": [
      {
        "slot": "?principal",
        "value": {
          "ty": "User",
          "eid": "2"
        }
      }
    ]
  },
  {
    "template_id": "test_template",
    "result_policy_id": "test_template_result2",
    "instantiations": [
      {
        "slot": "?principal",
        "value": {
          "ty": "User",
          "eid": "1"
        }
      }
    ]
  }
]
```

The inner `"instantiations":` is a list because you could hypothetically instantiate both the `?principal` and the `?resource` for one `result_policy_id`

**Comment by jamiewinder** [comment]
Thanks! I suspect this is more a case of me misinterpreting 'instantiations' to mean an instantiation of the whole template rather than of a placeholder in the template. When I think of it that way, this actually makes perfect sense!

I suspect this can be closed.

**Comment by john-h-kastner-aws** [comment]
The precise issue you raised here is still valid. `"slot":"?principal",` showing up twice is something we can detect and report an error for, which should make it nicer to develop language bindings against this interface.

**Comment by aaronjeline** [comment]
Fixed by 365
