### ISSUE TITLE
docs.rs documentation improvement

### ISSUE THREAD

**Issue by mwhicks1** [cedar-policy/cedar#362]
### Category

Documentation and code comments

### Describe the feature you'd like to request

On the Rust crate documentation (e.g., https://docs.rs/cedar-policy/latest/cedar_policy/) there are no usage examples on the landing pages, just snippet examples for the particular API calls. When you get to the landing page, you are looking for help, but instead you get a long list of types and API calls with no explanation.

I like the worked example we have on the [crates.io page for cedar-policy](https://crates.io/crates/cedar-policy); could we something like that for our various packages, too? I see this is done for other Rust packages, e.g., https://docs.rs/graph/latest/graph/ and https://docs.rs/bigdecimal/latest/bigdecimal/ as two random cases.

### Describe alternatives you've considered

Not really. Doing nothing = status quo.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by john-h-kastner-aws** [comment]
A low-effort improvement to the top level docs could be using `#![doc = include_str!("../README.md")]` to include the readme verbatim in the crate docs, getting the example we have there for free. The exact text/examples we want in each place may be different though.
