### ISSUE TITLE
Improve parse error message on incorrect template slot

### ISSUE THREAD

**Issue by john-h-kastner-aws** [cedar-policy/cedar#391]
For a policy `permit(principal == ?resource, action, resource)` the parse error message is `expected a entity uid or template slot, found a ??resource statement`. First, it's printing `??resource` instead of `?resource` (easy fix) and second it's confusing that it expects a `templates slot` even though it found `?resource`. It should clarify that is specifically expects `?principal`.

**Comment by svanderbleek** [comment]
I found the ParseError is [happening](https://github.com/cedar-policy/cedar/blob/main/cedar-policy-core/src/parser/cst_to_ast.rs#L1617) but the context is lost on me. I see the [?](https://github.com/cedar-policy/cedar/blob/main/cedar-policy-core/src/parser/cst_to_ast.rs#L1600) being inserted but can I simply remove that there without breaking other uses? Then I'm not sure how to clarify as described. Maybe this is a little complicated for a first issue.

**Comment by john-h-kastner-aws** [comment]
The parser and following CST to AST conversion is a little convoluted, so perhaps not a first issue.  

For the `?`, I'm confident that's just a matter of deleting the extra `?`. 

For the rest of the error text improvement, it will come down to tracking down [where the value of `T::err_str()`](https://github.com/cedar-policy/cedar/blob/b85c5e87539a0c05e2db6141a1c5defd0fa9cc39/cedar-policy-core/src/parser/cst_to_ast.rs#L1659C50-L1659C50) is coming from. It looks like there's some type level shenanigans happening there.

**Comment by svanderbleek** [comment]
@john-h-kastner-aws I believe it is [here](https://github.com/cedar-policy/cedar/blob/b85c5e87539a0c05e2db6141a1c5defd0fa9cc39/cedar-policy-core/src/parser/cst_to_ast.rs#L918C10-L918C38).

**Comment by svanderbleek** [comment]
By taking `var` to string [here](https://github.com/cedar-policy/cedar/blob/b85c5e87539a0c05e2db6141a1c5defd0fa9cc39/cedar-policy-core/src/parser/cst_to_ast.rs#L1642) we can see the mismatch, how to communicate that exactly I'm not sure though.

**Comment by cdisselkoen** [comment]
Resolved by #411
