### ISSUE TITLE
Make options consistent across CLI sub-commands

### ISSUE THREAD

**Issue by john-h-kastner-aws** [cedar-policy/cedar#403]
### Category

Other

### Describe the feature you'd like to request

The CLI subcommands do not consistently use the same long and short names for options. 

For example, most commands take a Cedar policy file as input using the `--policies` and `-p` options.

* ~~`authorize` accepts only the long option `--policies` for the policies file. The short option `-p` specifies the principal.~~
* ~~`evaluate` does not accept a policy file, instead reading expression from an argument, but does use the short option `-p` for the principal.~~
* ~~`validate` accepts the long option `--policies` or the short options `-p` for policies.~~
* `check-parse` accepts `--policies`, `-p`, or policy text from standard input.
* ~~`link` accepts `--policies-file` or `-p`.~~
* `format` accepts the policies file as a positional argument after any other options, or from standard input if no positional arguments are provided. 

There may be other ways that the sub-commands are inconsistent.

**Comment by john-h-kastner-aws** [comment]
The `format` inconsistency still isn't resolved, and `check-parse` reads from stdin unlike most other.

**Comment by svanderbleek** [comment]
@john-h-kastner-aws That's what I was hoping to bring up discussion of, do you have an idea of how it should be fixed? Take away positional and make it by argument only for format? Remove standard input from the ones that use it or add standard input to the ones that don't? Thanks.

**Comment by john-h-kastner-aws** [comment]
IMO the stdin option only makes sense when there's only one input file (`check-parse` and `format`), so we can justify leaving these as these as reading from stdin when there's not explicit policy file.

If we make `format` use `-p` and `--policies` instead of a positional argument, then I think we can call it good.
