### ISSUE TITLE
Improve parser errors around `is`

### ISSUE THREAD

**Issue by john-h-kastner-aws** [cedar-policy/cedar#409]
### Category

Other

### Describe the feature you'd like to request

There is some room to provide more specific parse errors for malformed `is` expressions.

To make this issue concrete: `is` currently parsers expecting a `Name` for the entity type. If the following text doesn't parse as a `Name` the user sees a cryptic "expected token" error message (see #176). We could improve these errors message by instead expecting an `Expr`, and then raising an specific error in the CST to AST conversion if the `Expr` isn't a `Name`.

Other parse error improvements improvements are covered by #176, #391, #407

### Describe alternatives you've considered

.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cdisselkoen** [comment]
To be even more concrete, here are some `is` parse errors (as of #396) that could be improved:

```
permit(principal in Group::"friends" is User, action, resource);
current error: "expected a entity uid or template slot"

permit(principal is User::"alice", action, resource);
current error: "unexpected token `"alice"`"

permit(principal is User in 1, action, resource);
current error: "expected a entity uid or template slot, found a `literal` statement"

permit(principal, action, resource is 1);
current error: "unexpected token `1`"

permit(principal is User in ?resource, action, resource);
current error: "expected a entity uid or template slot"

permit(principal, action, resource) when { principal is 1 };
current error: "unexpected token `1`"
```
