### ISSUE TITLE
Error message is misleading when defining an attribute incorrectly in schema JSON

### ISSUE THREAD

**Issue by cdisselkoen** [cedar-policy/cedar#417]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Schemas and Validation

### Describe the bug

For the below schema, the reported error is
```
unknown field `baz`, expected one of `type`, `element`, `attributes`, `additionalAttributes`, `name`
```

This is misleading because `baz` is a completely valid field (attribute name), and changing `baz` to some other string (like the ones listed) will not fix the problem.

Instead, the issue is in the `bar` field.  The set element type was listed as `"Long"` instead of `{ "type": "Long" }`. 

If you fix the set-element mistake, you see that a similar mistake was made in the `baz` field, but that one actually has a reasonable-ish error message once you fix the set-element mistake:
```
invalid type: string "Boolean", expected struct TypeOfAttribute
```

This actually points to the correct problem location (`"Boolean"`), and from this error message an end-user could probably decipher a hint that they need a JSON object instead of just the string `"Boolean"`.  (This error message itself could definitely be improved, too; for instance, we could suggest that you need `{ "type": ... }` instead of using the cryptic term `TypeOfAttribute`; and we could even perhaps suggest `{ "type": "Boolean" }` in this particular case.)

### Expected behavior

A better error message -- at least one that points to the `bar` attribute instead of `baz`, and ideally a reasonable suggested fix.  See above.

### Reproduction steps

Try to parse the schema given below

### Code Snippet

```json
{ "": {
   "entityTypes": {
       "a": {
           "shape": {
               "type": "Record",
               "attributes": {
                    "foo": { "type": "Entity", "name": "b" },
                    "bar": { "type": "Set", "element": "Long" },
                    "baz": { "type": "Record", "attributes": { "z": "Boolean" } }
               }
           }
       },
       "b": {}
   }
} }
```

**Comment by john-h-kastner-aws** [comment]
That's a subtle bug.

I think it's an unintended consequence of the [behavior noted here](https://github.com/cedar-policy/cedar/blob/04874155a2aebb8aa6ddb0bcdd049287493476f1/cedar-policy-validator/src/schema_file_format.rs#L279), but I haven't fully figured it out yet.

**Comment by john-h-kastner-aws** [comment]
Another example of this class of error came up recently. The only difference is that the error on the top level attribute instead of a nested attribute.


```json
{
  "": {
    "entityTypes": {
      "User": {
        "shape": {
          "type": "Record",
          "attributes": {
            "foo": {
              "type": "Record",
              "element": { "type": "Long" }
            },
            "bar": { "type": "Long" }
          }
        }
      }
    },
    "actions": {}
  }
}
```

error is

```
  × failed to parse schema from file test.cedarschema.json
  ╰─▶ unknown field `bar`, expected one of `type`, `element`, `attributes`, `additionalAttributes`, `name` at line 12 column 17
```

FWIW, this issue should be easy to fix if we don't mind having slight less helpful error messages when a JSON schema contains parse errors inside unexpected fields.  It would complain about the error in the field before complaining about the existence of the field. This error as it stands is bad enough that IMO it's easily worth it.
