### ISSUE TITLE
Eliminate the "false errors" mentioned in a TODO comment in cst_to_ast.rs

### ISSUE THREAD

**Issue by cdisselkoen** [cedar-policy/cedar#439]
### Category

Internal refactors/changes

### Describe the feature you'd like to request

This comes from a TODO in cedar-policy-core/src/parser/cst_to_ast.rs.

```
        // Starting off with a failure and filtering items from the accessor list
        // can cause false error messages. We consider this acceptable for now because
        // they only occur along side a real error.
        // TODO: eliminate the false errors (likely with `Option`s inside `AstAccessor`)
 ```

### Describe alternatives you've considered

There might be multiple ways to refactor to achieve the desired outcome

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by john-h-kastner-aws** [comment]
Closing based on discussion on #945. It's not clear what errors this issues references, and we've changed the implementation of the relevant function enough that they issue might not apply any more.
