### ISSUE TITLE
Consider a different implementation of `typecheck_restricted_expr_against_schematype()`

### ISSUE THREAD

**Issue by cdisselkoen** [cedar-policy/cedar#440]
### Category

Internal refactors/changes

### Describe the feature you'd like to request

This comes from a TODO in the code in cedar-policy-core/src/entities/conformance.rs (as of this writing).

Currently, Core typechecks a restricted expression against a Core `SchemaType` by first calculating the `SchemaType` of the restricted expression, and then determining if the two `SchemaType`s are "consistent".  It may be less confusing, more efficient, and/or more precise to just typecheck directly.

In [a comment on #430](https://github.com/cedar-policy/cedar/pull/430#discussion_r1395940271), @khieta says she prefers the code as-is because it prevents duplication and reuses `schematype_of_restricted_expr()`.  This concern should be balanced against the one above.

Either we should change the implementation, or we should just remove the TODO if we determine the current implementation is the most desirable.

### Describe alternatives you've considered

We can also refactor/adjust `schematype_of_restricted_expr()` and/or `SchemaType::is_consistent_with()` if that would make things clearer.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by andrewmwells-amazon** [comment]
https://github.com/cedar-policy/cedar/pull/1177 adds a dedicated method here (though it still could be optimized further).

**Comment by john-h-kastner-aws** [comment]
Resolved by #1177, #1190, #1194, and #1197 which together remove `schematype_of_restricted_expr` entirely and re-implement this function to typecheck directly.
