### ISSUE TITLE
Allow writing polocies with complex principal expressions

### ISSUE THREAD

**Issue by davidMcneil** [cedar-policy/cedar#464]
### Category

Cedar language features, Cedar syntax changes/additions

### Describe the feature you'd like to request

"or" logic
```
permit (
    principal in App::UserGroup::"Group1" || principal in App::UserGroup::"Group2",
    action == App::Action::"someAction",
    resource in App::Resource::"someResource
);
```

"and" logic
```
permit (
    principal in App::UserGroup::"Group1" && principal in App::UserGroup::"Group2",
    action == App::Action::"someAction",
    resource in App::Resource::"someResource
);
```

### Describe alternatives you've considered

"or" logic could be represented with a set but "and" logic would still be nice

```
permit (
    principal in [App::UserGroup::"Group1", principal in App::UserGroup::"Group2"],
    action == App::Action::"someAction",
    resource in App::Resource::"someResource
);
```

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by shaobo-he-aws** [comment]
@davidMcneil Thank you for your interest in Cedar. You can find info and examples about Cedar logic operators [here](https://docs.cedarpolicy.com/policies/syntax-operators.html#operators-logical). I tentatively closed this issue. Please feel free to reopen it should you have further questions.

**Comment by davidMcneil** [comment]
Thanks for the replies and suggestions! `when` clause is the alternative I am currently using, but lose out on any ability to index the policies as you mention. `action` currently accepts a set when using the `in` operator. Would the team be open to something similar for the `principal`? And maybe an "in all" operator (with a better name :smile:) to support the `&&` case?
