### ISSUE TITLE
Get residual results even when concrete result is achieved

### ISSUE THREAD

**Issue by 0x00A5** [cedar-policy/cedar#474]
### Category

User level API changes

### Describe the feature you'd like to request

With the current `cedar_policy_core::Authorizer::is_authorized_core` method implementation, when satisfied permits are available and no satisfied or residual forbids are found, the `cedar_policy::Authorizer` responds with the `Allow` decision and only the satisfied permits policy set.

However, users can also be interested in the residual permits even though these policies do not affect the `Allow` decision (or the residual forbids when there are satisfied forbids).

For example, a user may want to collect all the annotations of policies that contribute to a `Allow` decision. But due to some unknowns, residual permits policies will be neglected from the response, while ideally the user could then resolve these unknowns and re-evaluate the residual permit policies to collect all annotations.

One way to achieve this is by tweaking the input of a existing method `cedar_policy_core::Authorizer::evaluate_policies` and expose it as a public method in the `cedar_policy` crate. The method would just return evaluation results and their corresponding policies and leave it to the users in terms of what to do next.

### Describe alternatives you've considered

Wrap the `cedar_policy_core::Evaluator` struct and expose it in `cedar_policy` crate.

### Is this something that you'd be interested in working on?

- [x] 👋 I may be able to implement this feature request
- [x] ⚠️ This feature might incur a breaking change

**Comment by shaobo-he-aws** [comment]
Hi @0x00A5. Thank you for your interest in Cedar. The Cedar team is currently reviewing your issue and we will get back to you as soon as we make a decision.

**Comment by sarahcec** [comment]
Hi Yuan, we've reviewed this issue, and we think it would be a valuable addition to Cedar. You indicated in the issue that you'd be willing to work on it. Please feel free to send us a pull request. If you have questions or want guidance please join the Cedar slack https://communityinviter.com/apps/cedar-policy/cedar-policy-language and Shaobo and I would be happy to help.

**Comment by 0x00A5** [comment]
Great, please feel free to assign it to me - I plan to start working on it shortly

**Comment by shaobo-he-aws** [comment]
> Great, please feel free to assign it to me - I plan to start working on it shortly

Awesome. Please let us know if you need any info or help.

**Comment by sarahcec** [comment]
We're targeting the next release (3.0.2) for the week of January 22. If you want to try to get this in before then, we can roll it in.
