### ISSUE TITLE
Test suite for error messages

### ISSUE THREAD

**Issue by khieta** [cedar-policy/cedar#479]
### Category

Internal refactors/changes

### Describe the feature you'd like to request

It would be useful to have a test suite that focuses on testing error messages. This would help us keep track of all our current error messages, and easily see how they are impacted by code changes. We currently test some error messages (in unit tests and integration tests), but our testing is not comprehensive and is spread throughout the code base.

### Describe alternatives you've considered

N/A

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by john-h-kastner-aws** [comment]
I came across a tool that could help automate this: https://github.com/mitsuhiko/insta

**Comment by khieta** [comment]
Based on recent PRs improving error message tests (e.g., #996, #1008), I think the need for error testing is sufficiently addressed by the testing utilities introduced by #477.

Our error message testing still isn't complete (there are still some uncovered variants), but I feel comfortable closing this issue. Going forward, we should make an effort to check that new error variants are properly tested using the utilities in `cedar-policy-core/src/test_utils.rs` 🙂
