### ISSUE TITLE
Reuse CI workflows to build downstream dependencies

### ISSUE THREAD

**Issue by john-h-kastner-aws** [cedar-policy/cedar#488]
### Category

Internal refactors/changes

### Describe the feature you'd like to request

The [CI workflow used by this repository](https://github.com/cedar-policy/cedar/blob/main/.github/workflows/build_downstream_deps.yml) to build the downstream dependencies in cedar-spec, cedar-examples, and cedar-java duplicates the workflows found in those individual repositories. We should [reuse these workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows) so that CI doesn't break when a change made in a downstream repository isn't copied here.

Relevant workflows:

* cedar-examples: https://github.com/cedar-policy/cedar-examples/blob/main/.github/workflows/ci.yml
* cedar-java: https://github.com/cedar-policy/cedar-java/blob/main/.github/workflows/ci.yml
* cedar-spec: https://github.com/cedar-policy/cedar-spec/blob/main/.github/workflows/ci.yml

### Describe alternatives you've considered

.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by andrewmwells-amazon** [comment]
- [ ] tinytodo
- [ ] cedar-rust-hello-world
- [ ] cedar-example-use-cases
- [ ] cedar-java
- [ ] cedar-spec

**Comment by john-h-kastner-aws** [comment]
The current reusable downstream builds turn out not to work for PRs coming from forks. See this failed workflow: https://github.com/cedar-policy/cedar/actions/runs/7451426259/job/20272524590

**Comment by john-h-kastner-aws** [comment]
Fork build failure was fixed by https://github.com/cedar-policy/cedar-examples/pull/90

**Comment by andrewmwells-amazon** [comment]
Java CI successfully fails for broken [PR](https://github.com/cedar-policy/cedar/actions/runs/8529036529/job/23363951815?pr=775) and [Fork](https://github.com/cedar-policy/cedar/actions/runs/8529220873/job/23364530934?pr=770).

**Comment by khieta** [comment]
Reusable CI added for `cedar-spec` (the last hold out) in [cedar-spec#269](https://github.com/cedar-policy/cedar-spec/pull/269). Marking this issue as resolved.
