### ISSUE TITLE
Report source locations for undefined entity type and action errors in validation

### ISSUE THREAD

**Issue by john-h-kastner-aws** [cedar-policy/cedar#522]
### Category

Other

### Describe the feature you'd like to request

The validator error messages for undefined entity types and actions don't record source locations even though they easily could.

We currently get an error like 

```
  × policy set validation failed
  ╰─▶ validation error on policy `policy0`: unrecognized entity type `AWS`
  help: did you mean `List`?
```

which is good, but would be better if we pointed to the source location where the entity type is used.

We also don't track source locations for `InvalidActionApplication`, but fixing this requires more work in #521.

### Describe alternatives you've considered

.

### Additional context

.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by Swolebrain** [comment]
I want this badly

**Comment by shaobo-he-aws** [comment]
Would this feature require #531? I think type reference resolution when parsing human readable schemas can report these errors but may not actually do it.

**Comment by john-h-kastner-aws** [comment]
no, this issues only requires a source location in the policy

**Comment by chrnorm** [comment]
Support for this would help make our [Policy Validation GitHub Action](https://github.com/common-fate/cedar-validate-action) easier to maintain - we ended up adding a second round of policy parsing in our Cedar WASM fork to get the ranges for the policy ID.
