### ISSUE TITLE
Avoid the clone in typechecking

### ISSUE THREAD

**Issue by aaronjeline** [cedar-policy/cedar#537]
### Category

Internal refactors/changes

### Describe the feature you'd like to request

Avoid the `clone` of expressions in `cedar-policy-core/src/entities/conformance.rs`, perhaps by converting to`BorrowedRestrictedExpr` instead of `RestrictedExpr`

### Describe alternatives you've considered

Status quo

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cdisselkoen** [comment]
I believe this is referring to [this clone](https://github.com/cedar-policy/cedar/blob/d1f1185ed55bf3126e3cc14271e7b66aa9895804/cedar-policy-core/src/entities/conformance.rs#L153).  Note that `PartialValue` may contain a full `Expr` in the `Residual` case.  But, based on comments in that function, we only call this function with `value`s which are entity attributes.  This means we shouldn't have large `Expr`s hidden in these `PartialValue`s, so this `clone()` is not a large cost and not worth optimizing.
