### ISSUE TITLE
Refactor `Context` to enforce its invariant statically

### ISSUE THREAD

**Issue by aaronjeline** [cedar-policy/cedar#541]
### Category

Internal refactors/changes

### Describe the feature you'd like to request

`cedar_policy_core::ast::request::Context` looks like:
```rust
/// `Context` field of a `Request`
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct Context {
    /// Context is internally represented as a `PartialValue`
    ///
    /// Context is serialized as a `RestrictedExpr`, for partly historical reasons.
    //
    // INVARIANT(ContextRecord): This must be a `Record`: either
    // `PartialValue::Value(Value::Record)`, or
    // `PartialValue::Residual(Expr::Record)`, or an appropriate unknown
    #[serde(flatten)]
    context: PartialValueSerializedAsExpr,
}
```
We should enforce this invariant statically if possible

### Describe alternatives you've considered

Status quo, enforce it dynamically. 

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by shaobo-he-aws** [comment]
I'd like to prioritize this issue as it's been shown to help multiple PRs.

**Comment by khieta** [comment]
One PR this would have helped is #1027. (Note that the PR also updates the `ContextRecord` invariant to accurately reflect that a `Context` can never be purely unknown).  

I think the right solution here is to store the context contents as a hash map (or similar data structure) instead of a record expression.
