### ISSUE TITLE
Regenerate corpus tests

### ISSUE THREAD

**Issue by khieta** [cedar-policy/cedar#552]
### Category

Internal refactors/changes

### Describe the feature you'd like to request

The [corpus tests](https://github.com/cedar-policy/cedar/tree/main/cedar-integration-tests/corpus_tests) are intended to check edge cases in the Cedar authorizer/validator that we may have missed writing a unit test for. They are auto-generated by our DRT infrastructure in [`cedar-spec`](https://github.com/cedar-policy/cedar-spec). The current tests were uploaded with our initial commit in May 2023, and have been manually updated to account for some changes (e.g., new error messages), but we have not fully regenerated them in a while. This means that language features that were added after May 2023 (like `is`) are not covered in the current tests.

We should regenerate the corpus tests to account for new language features.

### Describe alternatives you've considered

A more permanent solution would be to automatically regenerate the corpus tests at regular intervals (say, every week). A downside of this is that it would clutter our commit history with large diffs -- maybe a reason to move the corpus tests to be hosted elsewhere?

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by john-h-kastner-aws** [comment]
While doing this we should update file names to match out current conventions:
* Policy files are `.cedar` instead of `.txt`
* Schema files are `.cedarschema.json` instead of just `.json`
* Entity data should be `.json` instead of `.txt`

Hopefully these files are only referenced in the `schema`, `policies` and `entities` fields in the main test jsons files.

**Comment by khieta** [comment]
Resolving this issue since corpus tests are now the responsibility of https://github.com/cedar-policy/cedar-integration-tests
