### ISSUE TITLE
Misleading messages for errors on `==` in action scope

### ISSUE THREAD

**Issue by john-h-kastner-aws** [cedar-policy/cedar#563]
### Category

Other

### Describe the feature you'd like to request

The error message for an invalid equality in the action scope is misleading in two cases.

If you write an equality with an invalid expression on the right, it expects `an entity uid or set of entity uids`, but `==` doesn't accept a set.

```console
jkastner@88665a03aa97 cedar % cargo run check-parse <<<'permit(principal, action == 1, resource);'
    Finished dev [unoptimized + debuginfo] target(s) in 0.58s
     Running `target/debug/cedar check-parse`
  × failed to parse policy set
  ╰─▶ expected an entity uid or set of entity uids, found literal `1`
   ╭─[<stdin>:1:1]
 1 │ permit(principal, action == 1, resource);
   ·                             ─
   ╰────
```

If we follow the advice and try it with a set, it now claims to want a `single entity uid or a template slot`, but a slot isn't allowed in the action scope.

```console
jkastner@88665a03aa97 cedar % cargo run check-parse <<<'permit(principal, action == [Action::"foo"], resource);'
    Finished dev [unoptimized + debuginfo] target(s) in 0.27s
     Running `target/debug/cedar check-parse`
  × failed to parse policy set
  ╰─▶ the right hand side of equality in the policy scope must be a single entity uid or a template slot
   ╭─[<stdin>:1:1]
 1 │ permit(principal, action == [Action::"foo"], resource);
   ·                             ───────────────
   ╰────
```

### Describe alternatives you've considered

.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by john-h-kastner-aws** [comment]
Part of the issue here seems to be that the error variant used for `action == [...]` is `InvalidScopeEqualityRHS`, but this should instead be reported as `RefCreationError`. This is the only place we use `InvalidScopeEqualityRHS`, so we should then remove that variant.

**Comment by cdisselkoen** [comment]
Just checking that #818 addressed both of the cases described above?  The description of #818 doesn't explicitly say it addresses the second case.

**Comment by john-h-kastner-aws** [comment]
Both are fixed

https://github.com/cedar-policy/cedar/blob/489af84107bc30de493dfb1fb85e047de0ce955d/cedar-policy-core/src/parser/cst_to_ast.rs#L5201-L5204
