### ISSUE TITLE
Misleading error messages for entity references

### ISSUE THREAD

**Issue by shaobo-he-aws** [cedar-policy/cedar#567]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Cedar Parser

### Describe the bug

```
cargo run check-parse
    Finished dev [unoptimized + debuginfo] target(s) in 0.19s
     Running `target/debug/cedar check-parse`
permit(principal, action, resource == true::"");         

  × failed to parse policy set
  ╰─▶ unexpected token `""`
   ╭─[<stdin>:1:1]
 1 │ permit(principal, action, resource == true::"");
   ·                                             ─┬
   ·                                              ╰── expected `action`, `context`, `else`, `false`, `forbid`, `has`, identifier, `if`, `in`, `is`, `like`, `permit`, `principal`, `resource`, `then`, `true`, `unless`, or `when`
 2 │ 
   ╰────
```

### Expected behavior

The error message should point out that `true` cannot be part of a `Name`.

### Reproduction steps

NA

### Code Snippet

```rust
// Put your code below this line.

```

### Log output

```
// Put your output below this line

```

**Comment by john-h-kastner-aws** [comment]
Possibly the same root cause as  #407
