### ISSUE TITLE
Support partial evaluation in CLI

### ISSUE THREAD

**Issue by Neio** [cedar-policy/cedar#57]
### Category

Other

### Describe the feature you'd like to request

Be able to do partial evaluation in the CLI

### Describe the solution you'd like

Introduce an optional parameter "--partial" in the CLI, so to change the entity mode to partial and be able to do partial authorization and give residual result.

### Describe alternatives you've considered

None

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by shaobo-he-aws** [comment]
Hi @Neio, thank you for your interest in Cedar. Partial evaluation is currently an experimental feature and not ready for production use. Hence, we cannot accept any PR related to this feature. I hope you can understand it.
