### ISSUE TITLE
Escapes sequences mangled by JSON round-trip

### ISSUE THREAD

**Issue by john-h-kastner-aws** [cedar-policy/cedar#618]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Cedar Parser

### Describe the bug

Starting with policy containing a string with an escape sequence `"\n"`, if we serialize the policy to JSON and then construct a new policy from that JSON, the string becomes `"\\n"`.  

```rust
    let policy_src = r#"permit(principal, action, resource) when { "\n" };"#;
    let p1 = Policy::from_str(policy_src).unwrap();
    println!("{p1}"); // permit(principal, action, resource) when { "\n" };

    let json = p1.to_json().unwrap();
    println!("{json}"); // {"effect":"permit","principal":{"op":"All"},"action":{"op":"All"},"resource":{"op":"All"},"conditions":[{"kind":"when","body":{"Value":"\\n"}}]}

    let p2 = Policy::from_json(None, json).unwrap();
    println!("{p2}"); // permit(principal, action, resource) when { "\\n" };
```

### Expected behavior

JSON roundtrip should produce an equivalent policy 

### Reproduction steps

.

### Code Snippet

```rust
// Put your code below this line.

```

### Log output

```
// Put your output below this line

```

**Comment by shaobo-he-aws** [comment]
The root cause of this bug is that CST to EST conversion did not unescape raw strings so that `r#"\n"#` becomes JSON string `\\n`. We want strings (literals or eids) in EST and AST are the same (modulo differences in string escaping rules).
