### ISSUE TITLE
EST allows annotation identifiers that are forbidden in human formated policies

### ISSUE THREAD

**Issue by john-h-kastner-aws** [cedar-policy/cedar#623]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Cedar Parser

### Describe the bug

In this EST JSON, there is an annotation identifier `if`
```json
{
  "annotations": {
    "if": ""
  },
  "effect": "permit",
  "principal": {
    "op": "All"
  },
  "action": {
    "op": "All"
  },
  "resource": {
    "op": "All"
  },
  "conditions": []
}
```

We can parse this and obtain a `Policy` object, but printing that policy to a string gives

```
@if("") 
permit(principal, action, resource);
```

Which does not parse because `if` is a reserved identifier.

```rust
    let est = serde_json::json!(
        {
            "annotations": {
              "if": ""
            },
            "effect": "permit",
            "principal": {
              "op": "All"
            },
            "action": {
              "op": "All"
            },
            "resource": {
              "op": "All"
            },
            "conditions": []
        }
    );
    let p = Policy::from_json(None, est).unwrap();
    let human_src = p.to_string();
    Policy::from_str(&human_src).unwrap(); // This panics
```

### Expected behavior

.

### Reproduction steps

.

### Code Snippet

```rust
// Put your code below this line.

```

### Log output

```
// Put your output below this line

```

**Comment by john-h-kastner-aws** [comment]
See also #407 for general issues around special-cases for reserved identifiers

**Comment by shaobo-he-aws** [comment]
I think that any place where `Id` is required could have this issue.

**Comment by cdisselkoen** [comment]
#634 proposes to resolve this by just allowing Cedar reserved words as annotation keys, both in EST and human-format policies.
