### ISSUE TITLE
Arithmetic overflow validation

### ISSUE THREAD

**Issue by mattmccutchen-amazon** [cedar-policy/cedar#63]
### Category

Cedar validation features

### Describe the feature you'd like to request

We would like a way to verify in advance that policies will not raise arithmetic overflow errors during evaluation.

Runtime errors of any kind are a potential source of unintended behavior in users' policies, and the possibility of arithmetic overflow errors in particular makes certain kinds of reasoning about Cedar code difficult.

### Describe the solution you'd like

Enhance validation to be able to rule out arithmetic overflow errors.  In essence, the `Long` type will be parameterized with lower and upper bounds on the value.  We start by having the schema state the assumed bounds for each attribute of type `Long`.  Then, for each arithmetic operator in a policy, the validator will compute bounds for the result and report a validation error if the result bounds exceed the range of a Cedar `Long`.

Parts of the implementation:
- Extend the production schema parser to parse the bounds.
- Implement the new feature in the production validator.
- Add bounds to the definitional schema data structure, and implement the new feature in the definitional validator.
- Add DRT coverage of some kind for the new feature.  This would include adding the serialization code needed for the bounds to get from the Rust side to the Dafny side.
- In Dafny, prove that the validator is sound, i.e., if a policy passes validation, then it cannot raise an overflow error on inputs that conform to the schema.
- Extend "schema-based parsing" to enforce the bounds.

### Describe alternatives you've considered

At one point, we considered changing Cedar's integer type to be unbounded (so it could never "overflow"), but we were concerned that operating on "big integers" could become too slow.

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [X] ⚠️ This feature might incur a breaking change (Specifically: depending on the default behavior we end up choosing for attributes with unspecified bounds, policies that previously passed validation may now get errors about potential arithmetic overflow.)

**Comment by john-h-kastner-aws** [comment]
We've decided not to implement the feature described here, largely due to the small amount of usage arithmetic currently gets. See discussion on the related RFCs https://github.com/cedar-policy/rfcs/pull/39 and https://github.com/cedar-policy/rfcs/pull/36
