### ISSUE TITLE
Move integration testing code to its own crate

### ISSUE THREAD

**Issue by khieta** [cedar-policy/cedar#644]
### Describe the improvement you'd like to request

Currently the integration test format and related code is defined in the `cedar-policy` crate, which makes it difficult to refactor testing code without making breaking changes. We should move all of this to a separate crate (e.g., in the `cedar-integration-tests` folder) in the next major version of Cedar.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this internal improvement
- [X] ⚠️ This feature might incur a breaking change

**Comment by khieta** [comment]
Created a new testing crate in #707. Will leave this issue open until the old integration testing code is removed.

**Comment by john-h-kastner-aws** [comment]
Linking this with #820. Maybe even worth closing this if all remaining work is covered by that issue?

**Comment by khieta** [comment]
They're closely related -- this issue is to delete the `cedar-policy/integration_testing.rs` file and #820 is to delete the `cedar-integration-tests/` folder. 

I'll close this issue & add a note to the other. The more issues I leave open, the more I'll forget to close later 😅
