### ISSUE TITLE
EST Generator crashes with an invalid attribute name

### ISSUE THREAD

**Issue by aaronjeline** [cedar-policy/cedar#66]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+) and [discussions](https://github.com/cedar-policy/cedar/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Cedar Parser

### Describe the bug

Cedar EST generator crashes when attempting to generate an EST for a policy with an invalid attribute name.

### Expected behavior

EST generation should fail gracefully

### Reproduction steps

Given the following the policy:
```
permit(principal, action, resource) when { resource.name.like == "test" };
```
The cli can be crashed as follows:

``` bash
cargo run check-parse --policies ./policies.cedar
```
Resulting in:
```
thread 'main' panicked at 'not implemented: other idents?', cedar-policy-core/src/est/expr.rs:1187:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by aaronjeline** [comment]
Fixed.

**Comment by andrewmwells-amazon** [comment]
In https://github.com/cedar-policy/cedar/pull/68 and https://github.com/cedar-policy/cedar/pull/69
