### ISSUE TITLE
`IntoIterator` for `Entities`

### ISSUE THREAD

**Issue by cdisselkoen** [cedar-policy/cedar#680]
### Category

User level API features/changes

### Describe the feature you'd like to request

The public `Entities` type should support `.into_iter()` and the `IntoIterator` trait.  Today, it only supports `.iter()` which gives `&Entity` as the item type; but some users may want to consume the `Entities` and have `Entity` as the item type.  In particular, I'm imagining that users might want to do this in order to add more `Entities` and then give the larger set of entities back to `Entities::from_entities()` (at least until #612 is fixed).

### Describe alternatives you've considered

The status quo works, but requires users to clone each `Entity` if they want to rebuild another `Entities` object.

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cdisselkoen** [comment]
Actually [`Entities::add_entities()`](https://docs.rs/cedar-policy/latest/cedar_policy/struct.Entities.html#method.add_entities) is a reasonable alternative to `.into_iter()` followed by `::from_entities()`.  So this issue is not urgent.  It would probably still be good to provide `IntoIterator` though.

**Comment by cre4ture** [comment]
I thought I give it a try ;-)

**Comment by john-h-kastner-aws** [comment]
This was resolved by #713
