### ISSUE TITLE
Change CLI schema default to "human"

### ISSUE THREAD

**Issue by khieta** [cedar-policy/cedar#683]
### Category

CLI features/changes

### Describe the feature you'd like to request

Cedar policies and schemas support two formats: human-readable and JSON. You can change the format used in CLI commands using `--policy-format (human|json)` and `--schema-format (human|json)`.

The default for policies is `human` and the default for schemas is `json`. Now that we've released the new schema syntax, I think it's time to update the default to be `human` so the two are consistent.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [x] ⚠️ This feature might incur a breaking change

**Comment by cdisselkoen** [comment]
Big +1.  But, this is a breaking change so has to be held until 4.0.
