### ISSUE TITLE
Re-export core crate errors in cedar_policy crate

### ISSUE THREAD

**Issue by 0x00A5** [cedar-policy/cedar#695]
### Category

User level API features/changes

### Describe the feature you'd like to request

Today, many cedar_policy crate level APIs return errors that are defined by the cedar_policy_core crate making users have to depend on the core crate to use these errors. Until we standardize errors in the cedar_policy crate, we shall consider re-exporting core crate level errors in the cedar_policy crate so users can remove the core crate from their dependency list.

### Describe alternatives you've considered

Users depend on the core crate

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cdisselkoen** [comment]
Related: #745

**Comment by cdisselkoen** [comment]
Closing this in favor of #745.
