### ISSUE TITLE
De-duplicate code for checking if entity types exist in schema

### ISSUE THREAD

**Issue by john-h-kastner-aws** [cedar-policy/cedar#711]
### Describe the improvement you'd like to request

The human-readable schema format included some duplicate checks that check for the existence of an entity type when it is used in a schema. This checks is already done when construct a `ValidatorSchema` object, so it shouldn't be necessary to also perform the check when parsing the schema.  

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this internal improvement
- [ ] ⚠️ This feature might incur a breaking change

**Comment by memark** [comment]
Is this issue about refactoring out duplicate code to a common place, or to remove one of the duplicate checks altogether?
