### ISSUE TITLE
Update old parse error tests to check that the correct error is reported

### ISSUE THREAD

**Issue by john-h-kastner-aws** [cedar-policy/cedar#739]
### Describe the improvement you'd like to request

Some of our parse error tests assert that an expression fails to parse, but do not assert that it fails with the correct error kind.  We previously had an issue where a regression in the json schema parser was not noticed because of a test written in this way. We updated those tests, but we should also update these to avoid a similar regression in policy parsing.

For example, here we assert that exactly one error is raised, but we could assert that the error is due to `1` not being a valid attribute.
https://github.com/cedar-policy/cedar/blob/0f9df9589146900877c0508eb684ca9d4ab1d137/cedar-policy-core/src/parser/cst_to_ast.rs#L3340-L3353

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this internal improvement
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cdisselkoen** [comment]
Specifically we should use utilities like `expect_err()` in `cedar-policy-core/src/test_utils.rs`, or `expect_some_error_matches()` in `cedar-policy-core/src/parser.rs` (in its `pub(crate) mod test_utils`)

**Comment by khieta** [comment]
Resolved for the `cst_to_ast.rs` file by #902. But it looks like the issue may exist for parsing tests in `parser.rs`.
