### ISSUE TITLE
is_authorized should allow passing in EntityAttrValues

### ISSUE THREAD

**Issue by andrewmwells-amazon** [cedar-policy/cedar#77]
### Category

Cedar language features, User level API changes

### Describe the feature you'd like to request

Currently is_authorized is slow if you pass in enough entities with enough attributes. This is due to https://github.com/cedar-policy/cedar/blob/dcd5232721576f139c1ff30ad0695ddcb94f9b1d/cedar-policy-core/src/evaluator.rs#LL139C11-L139C11
which loops over all attributes in all entities.

It should be possible for users to compute EntityAttrValues once and use it for many authorization calls.

### Describe the solution you'd like

Modify the API so users have the option to compute EntityAttrValues before calling is_authorized additionally, modify is_authorized so it can take an EntityAttrValues (or some alternative) and skip this part of the computation.

### Describe alternatives you've considered

Alternatively, we could change from eager Entity Attribute evaluation to lazy evaluation with caching.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [X] ⚠️ This feature might incur a breaking change

**Comment by cdisselkoen** [comment]
related to (superseded by?) [RFC 23](https://github.com/cedar-policy/rfcs/pull/23)

**Comment by cdisselkoen** [comment]
Resolved (and partially rejected) by RFC 34
