### ISSUE TITLE
Omit JSON attributes with default value in human-to-json schema conversion

### ISSUE THREAD

**Issue by john-h-kastner-aws** [cedar-policy/cedar#776]
### Category

CLI features/changes

### Describe the feature you'd like to request

When converting from the Cedar human-friendly schema format to the JSON format, the CLI command `translate-schema` will explicitly include all JSON attribute with their default values. We should update this to omit attributes when they have their default value.

This is particularly important in the case of `additionalAttributes` which can _only_ be `true` if the `partial-validate` experimental feature is enabled, but schema translation command will always include `"additionalAttributes": false` on all record types. For example:

```bash
cedar translate-schema --schema <(echo 'entity Foo { attr: Long };') --direction human-to-json
```

gives

```json
{
  "": {
    "commonTypes": {}, // Should omit
    "entityTypes": {
      "Foo": {
        "memberOfTypes": [], // Should omit
        "shape": {
          "type": "Record",
          "attributes": {
            "attr": {
              "type": "Long",
              "required": true // Should omit
            }
          },
          "additionalAttributes": false // Should omit
        }
      }
    },
    "actions": {}
  }
}
```

### Describe alternatives you've considered

.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by khieta** [comment]
Related: #682 notes several ways that the output should be improved for the json-to-human direction.
