### ISSUE TITLE
Publish the WASM on NPM

### ISSUE THREAD

**Issue by sashee** [cedar-policy/cedar#778]
### Category

Other

### Describe the feature you'd like to request

It would be nice to be able to install the WASM-compiled version to a JS project from NPM.

### Describe alternatives you've considered

Currently I built it on my machine and put the result on GitHub, but that's not ideal.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by khieta** [comment]
Thanks for filing this issue! I think this is eventually the plan (cc/ @ncsze and @Swolebrain to confirm).

The WASM is currently only on our `main` branch, so I think we'd wait until it's officially "released" to publish it anywhere.

**Comment by junlarsen** [comment]
I'd love to access cedar's wasm build from npm. Is there anything I can do to help get this moving?

**Comment by Swolebrain** [comment]
I was waiting on an external contributor who had a _much_ nicer version of the validation function than what we wrote, but we can always publish it with some npm version 0.x to signal that the interface is unstable. I'll get around to it ASAP, I have everything i need

**Comment by Swolebrain** [comment]
https://www.npmjs.com/package/@cedar-policy/cedar-wasm

**Comment by Swolebrain** [comment]
https://www.npmjs.com/package/@cedar-policy/cedar-wasm

**Comment by junlarsen** [comment]
Awesome, thank you so much!
