### ISSUE TITLE
Cedar formatter reorders comments

### ISSUE THREAD

**Issue by shaobo-he-aws** [cedar-policy/cedar#787]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Other

### Describe the bug

Cedar formatter reorders comments in the following policy.

```cedar
permit(principal, action, resource == a // 1
// 2
::
// 3
"");
```
becomes
```cedar
permit (
  principal,
  action,
  resource ==
    // 3
    a // 1
    // 2
    ::""
);
```

### Expected behavior

The formatter should strive to keep the order of comments.

### Reproduction steps

```bash
echo 'permit(principal, action, resource == a // 1
// 2
::
// 3
"");' | cargo run format
```

### Code Snippet

```rust
// Put your code below this line.

```

### Log output

```
// Put your output below this line

```

**Comment by john-h-kastner-aws** [comment]
Does our property test for the formater only check for the presence of comments and not their ordering?

**Comment by shaobo-he-aws** [comment]
> Does our property test for the formater only check for the presence of comments and not their ordering?

Correct.
