### ISSUE TITLE
Automatically write formatted policy back into file

### ISSUE THREAD

**Issue by junlarsen** [cedar-policy/cedar#789]
### Category

CLI features/changes

### Describe the feature you'd like to request

It would be awesome if the `cedar format` command wrote the formatted policy back into the file if the policy was pulled from a file (when `policies_file != None`)

To prevent accidental overwrites, or bugs in the formatter (such as #787), I suggest we put it under a `-w/--write` flag.

### Describe alternatives you've considered

Manually copying the stdout into the file, but it's a little tedious, and it seems like a reasonable thing to support.

### Additional context

Currently I copy from stdout and write back into the file manually.

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cdisselkoen** [comment]
Sounds reasonable to me

**Comment by junlarsen** [comment]
Cool, I'll take a stab at implementing it :)
