### ISSUE TITLE
Add `--check` option to `format` subcommand

### ISSUE THREAD

**Issue by john-h-kastner-aws** [cedar-policy/cedar#796]
### Category

CLI features/changes

### Describe the feature you'd like to request

This option would cause the CLI to exit with `0` if the policy is already formatted and `1` otherwise. It could be useful for people using the cedar CLI as part of a CI workflow.  

### Describe alternatives you've considered

.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by junlarsen** [comment]
This seems like a nice and reasonable thing to have

I would be interested in implementing it :smiley:
