### ISSUE TITLE
Improve generated TypeScript Result types for Cedar WASM

### ISSUE THREAD

**Issue by chrnorm** [cedar-policy/cedar#806]
### Category

User level API features/changes

### Describe the feature you'd like to request

The `cedar-wasm` and `ffi` crates currently use `#[serde(untagged)]` quite extensively -- I assume to minimize serialisation overhead.

Here's an example:

```rust
#[derive(Tsify, Debug, Serialize, Deserialize)]
#[serde(untagged)]
#[tsify(into_wasm_abi, from_wasm_abi)]
pub enum AuthorizationResult {
    Success { response: InterfaceResponse },
    Error { errors: Vec<String> },
}
```

This results in TypeScript types like the following:

```typescript
export type AuthorizationResult = { response: InterfaceResponse } | { errors: string[] };
```

These types are quite difficult to work with in TypeScript -- I work with TypeScript fairly frequently and rely on language server autocomplete to help me work with new SDKs. When using the my prerelease build of the Cedar WASM SDK I was surprised to find no autocomplete suggestions in my IDE for the result type above, which makes it more difficult to discover the available attributes on the result type.

<img width="431" alt="image" src="https://github.com/cedar-policy/cedar/assets/17420369/9e1caf65-eb92-42a5-ae09-12556f0457f0">

The approach I've seen in many libraries is to instead use a tagged representation of the struct. For example:

```
export type AuthorizationResult = { response: InterfaceResponse, type: "success" } | { errors: string[], type: "error" };
```

This helps immensely with the TypeScript developer experience:

<img width="432" alt="image" src="https://github.com/cedar-policy/cedar/assets/17420369/5f0d1df7-cdcc-49c1-acb5-1c370723fac3">
<img width="737" alt="image" src="https://github.com/cedar-policy/cedar/assets/17420369/9691dcfd-076a-45a1-87fd-623847bf40e4">

This is a matter of changing `#[serde(untagged)]` to `#[serde(tag = "type")]`, although we may want to limit this to the WASM crate only.

### Describe alternatives you've considered

I hit this problem when authoring a [GitHub Action for validating Cedar policies](https://github.com/common-fate/cedar-validate-action) and ended up forking the package and implementing `#[serde(tag = "type")]` myself on the structs I was using for validation

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by Swolebrain** [comment]
We considered that. We opted for the current approach to bias towards an error-first convention:

```
if ('errors' in result) {
  //handle the error
  //early return
}
```

Once you're past that early return, typescript has no problem giving you syntax hints. 

Notice in the screenshot of your suggested approach, the only thing it _can_ show in intellisense is `type`, because that's the only property that's present in both members of the union.

With the current approach, have flatter types for the relevant happy case, with less nesting. These allows some of our result unions to be like `TypeIActuallyWantWithoutNesting | { errors: string[]}`

For instance:
```
export type JsonToPolicyResult = { policyText: string } | { errors: string[] };
export type PolicyToJsonResult = { policy: Policy } | { errors: string[] };
export type CheckParsePolicySetResult = { policies: number; templates: number } | { errors: string[] };
export type CheckParseTemplateResult = { slots: string[] } | { errors: string[] };
export type FormattingResult = { formattedPolicy: string } | { errors: string[] };
```

**Comment by aaronjeline** [comment]
completed by #824
