### ISSUE TITLE
Delete the `cedar-integration-tests` folder

### ISSUE THREAD

**Issue by khieta** [cedar-policy/cedar#820]
### Describe the improvement you'd like to request

Now that the integration tests have a new home (https://github.com/cedar-policy/cedar-integration-tests), we should delete the the local (outdated) `cedar-integration-tests` folder.

This is currently **blocked** by [cedar-java#130](https://github.com/cedar-policy/cedar-java/issues/130). All other repositories (`cedar`, `cedar-spec`, `cedar-go`) have been migrated to the new tests. Hopefully this issue can be addressed once we've completed #757.

_Edit:_ We should also delete the `cedar-policy/integration_testing.rs` file, the contents of which were deprecated in #707.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this internal improvement
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cdisselkoen** [comment]
The relevant part of #757 was covered in #793, so I think the only work needed is cedar-policy/cedar-java#130 and then actually updating the Java integration tests to point at the new folder.
