### ISSUE TITLE
Return a parse error for obviously ill-typed expressions

### ISSUE THREAD

**Issue by khieta** [cedar-policy/cedar#85]
### Category

Cedar grammar changes/additions

### Describe the feature you'd like to request

In general, the AST type tries to represent only well-typed policies, but there are a few exceptions.

For example, the parser currently allows expressions like `"foo".some_ident` and `1["some string"]` even though these are clearly ill-typed, and will result in type errors at during authorization (or validation).

### Describe the solution you'd like

Make terms of the form `LITERAL {Access}` a parse error to make these "obvious" errors easier to catch. 

The easiest way to do this is probably to extend the `ExprOrSpecial` type in [cedar-policy-core/src/parser/cst_to_ast.rs](https://github.com/cedar-policy/cedar/blob/main/cedar-policy-core/src/parser/cst_to_ast.rs) with a general case for literals and then adjust the match cases in the implementation of `to_expr_or_special` for `cst::Member`.

### Describe alternatives you've considered

N/A

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cdisselkoen** [comment]
Given the title "Return a parse error for obviously ill-typed expressions", I had thought this issue would propose also catching things like `false < 2` or `false < resource.foo` at parse time.  Should we consider going further and doing that as well?

**Comment by john-h-kastner-aws** [comment]
I've been thinking we should close this in issue. At this point we're not looking to make breaking changes to the Cedar language, and moving an error from a possible run-time error (only if the ill-typed code is actually executed) to a parser-error could be very disruptive. Even if users should ideally be informed about this sort of mistake, I don't think we should do it as a breaking language change.

We should build this as part of a more general linter or schema-less (unsound) validation alternative instead.
