### ISSUE TITLE
CLI doesn't use source locations on schema errors

### ISSUE THREAD

**Issue by john-h-kastner-aws** [cedar-policy/cedar#948]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Other

### Describe the bug

For some human format schema parsing errors (at least those coming from lalrpop) should know the source location where the error occurred, but the CLI isn't printing them. 

For example, we might get this error is we try to declare the entity `User` twice

```
  × Error parsing schema: Duplicate declarations: `User`
  ╰─▶ Duplicate declarations: `User`
```

even though the schema parsing code captures the exact location

https://github.com/cedar-policy/cedar/blob/afd6a651808ae0090996c6eef74ad8c7b837f292/cedar-policy-validator/src/human_schema/err.rs#L393-L400

### Expected behavior

The CLI should include the source label

### Reproduction steps

.

**Comment by shaobo-he-aws** [comment]
I believe this is already handled by #1124.
