### ISSUE TITLE
Some `Diagnostic` implementations set `labels` without `source_code`

### ISSUE THREAD

**Issue by khieta** [cedar-policy/cedar#977]
### Describe the improvement you'd like to request

Some of our `Diagnostic` implementations set the `labels` function without setting `source_code`. These two fields are related (see the excerpt from `miette` below), so it doesn't make sense to set one without the other. The relevant error types seem to print fine (for some reason), but users who are consuming the `miette` errors programmatically may observe unexpected behavior. For example: I was trying to update [this testing code](https://github.com/cedar-policy/cedar/blob/b3a6eadd1f4f7923f5ac759b17f011ecef07d31a/cedar-policy-core/src/test_utils.rs#L225) to use the error's source text instead of the passed in source (which may or may not match the error), but found that the source text didn't exist for `ToCSTError`s.

```rust
    /// Source code to apply this `Diagnostic`'s [`Diagnostic::labels`] to.
    fn source_code(&self) -> Option<&dyn SourceCode> {
        None
    }

    /// Labels to apply to this `Diagnostic`'s [`Diagnostic::source_code`]
    fn labels(&self) -> Option<Box<dyn Iterator<Item = LabeledSpan> + '_>> {
        None
    }
```

Here's the list of error types doing this, from a quick scan through the code:
* [`UnexpectedSlotError`](https://github.com/cedar-policy/cedar/blob/b3a6eadd1f4f7923f5ac759b17f011ecef07d31a/cedar-policy-core/src/ast/policy.rs#L1424)
* [`ToCSTError`](https://github.com/cedar-policy/cedar/blob/b3a6eadd1f4f7923f5ac759b17f011ecef07d31a/cedar-policy-core/src/parser/err.rs#L552) 
* [`human_schema_errors::ParseError`](https://github.com/cedar-policy/cedar/blob/b3a6eadd1f4f7923f5ac759b17f011ecef07d31a/cedar-policy-validator/src/human_schema/err.rs#L155)
* [`ToJsonSchemaError`](https://github.com/cedar-policy/cedar/blob/b3a6eadd1f4f7923f5ac759b17f011ecef07d31a/cedar-policy-validator/src/human_schema/err.rs#L390C21-L390C38)
* [`schema_warnings::ShadowsBuiltinWarning`](https://github.com/cedar-policy/cedar/blob/b3a6eadd1f4f7923f5ac759b17f011ecef07d31a/cedar-policy-validator/src/human_schema/err.rs#L437C25-L437C46)
* [`schema_warnings::ShadowsEntityWarning`](https://github.com/cedar-policy/cedar/blob/b3a6eadd1f4f7923f5ac759b17f011ecef07d31a/cedar-policy-validator/src/human_schema/err.rs#L462)

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this internal improvement
- [ ] ⚠️ This feature might incur a breaking change

**Comment by john-h-kastner-aws** [comment]
This is the root cause of #948

**Comment by khieta** [comment]
I don't think this issue is too much work to fix. I'm just tired of playing with the parsing code, so I figured I'd throw it out there for someone else to pick up 😉

**Comment by shaobo-he-aws** [comment]
`ToJsonSchemaError`, `ShadowsBuiltinWarning`, and `ShadowsEntityWarning` are already handled via #1124.
