### ISSUE TITLE
Partial Evaluation

### ISSUE THREAD

**Issue by anwarmamat** [cedar-policy/cedar#98]
### Category

Cedar language features

### Describe the feature you'd like to request

A partial evaluator is an evaluator that evaluates an expression as far as possible in the presence of unknown values. The partial evaluator returns residual programs: the left over part of the program that was impossible to evaluate. 

Consider the following policy:
```
permit(principal, action, resource) where {
  if context.a { 
    context.b > 3
  else { 
    context.c
};
```
Perhaps `b` and `c` are expensive to compute, or are geographically distributed and expensive to get. We could imagine setting them to unknown, as follows:
```
{ 
  'a' : true, 
  'b' : unknown("b"),
  'c' : unknown("c"),
}
```
Partially evaluating should result in the residual expression:
```
unknown("b") > 3
```

### Describe the solution you'd like

N/A

### Describe alternatives you've considered

N/A

### Additional context

Adding this feature requires updating the Cedar core, Dafny definitional evaluator, and the differential and randomized tests (DRT). 

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [X] ⚠️ This feature might incur a breaking change

**Comment by khieta** [comment]
Closing this issue since it has already been implemented.
