### ISSUE TITLE
Policy validation with partial schema

### ISSUE THREAD

**Issue by anwarmamat** [cedar-policy/cedar#99]
### Category

Cedar validation features

### Describe the feature you'd like to request

The current approach to schema-based validation assumes that the schema file is complete: If an entity, or attribute, is not specified in the schema, then the validator assumes it does not exist. This means that, for example, an attribute access `x.f` when `f` is not present in the schema will result in a type error. In this document we sketch out a design for relaxing this constraint, calling the resulting algorithm `partial-schema validation`.

Partial-schema validation relaxes the assumption that the schema is complete. In other words, just because a policy references an attribute not mentioned in the schema, that doesn’t mean that the validator should flag an error. 

### Describe the solution you'd like

NA

### Describe alternatives you've considered

NA

### Additional context

NA

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by khieta** [comment]
Closing this issue in favor of [cedar-policy/rfc#8](https://github.com/cedar-policy/rfcs/pull/8). Please move any future discussion there.
